//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGESPKUL
    {
        public int SUBE_KODU { get; set; }
        public int KULLID { get; set; }
        public string LOGINNO { get; set; }
        public string YETKI { get; set; }
    }
}
