//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGKASAACIK
    {
        public int ACIKID { get; set; }
        public string STATUS { get; set; }
        public string ACIKLAMA { get; set; }
        public string MUHKODU { get; set; }
        public string CARIMUHASEBE { get; set; }
        public int SUBEKODU { get; set; }
        public decimal LIMIT { get; set; }
        public string FISNOYAZMA { get; set; }
        public string STOPAJKODU { get; set; }
        public decimal STOPAJORANI { get; set; }
        public string STOPAJSORGULANSIN { get; set; }
        public string PROJEKODU { get; set; }
        public decimal KDVORANI { get; set; }
        public string KDVSORGULANSIN { get; set; }
        public string MUHREFKOD { get; set; }
        public string MUHREFKODSORGULANSIN { get; set; }
    }
}
