//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGKAMPANYA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MGKAMPANYA()
        {
            this.MGKAMPANYACSKISIT = new HashSet<MGKAMPANYACSKISIT>();
            this.MGKAMPANYAURUN = new HashSet<MGKAMPANYAURUN>();
        }
    
        public string KAMPANYAKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string KOLISTOK { get; set; }
        public System.DateTime BASTAR { get; set; }
        public System.DateTime BITTAR { get; set; }
        public int FREQTIPI { get; set; }
        public int FREQINTERVAL { get; set; }
        public int FREQCOUNT { get; set; }
        public int FREQFACTOR { get; set; }
        public System.DateTime BASSAAT { get; set; }
        public System.DateTime BITSAAT { get; set; }
        public int FIYATTIPI { get; set; }
        public decimal SABITFIYAT { get; set; }
        public decimal ISKONTO { get; set; }
        public int ISKTIPI { get; set; }
        public int MFMIK { get; set; }
        public string KILIT { get; set; }
        public decimal MFISKONTOSU { get; set; }
        public string ISKNET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGKAMPANYACSKISIT> MGKAMPANYACSKISIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGKAMPANYAURUN> MGKAMPANYAURUN { get; set; }
    }
}
