//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGKOSULFIYAT
    {
        public int SIRA { get; set; }
        public int DETAYNO { get; set; }
        public byte TIP { get; set; }
        public string KOD { get; set; }
        public byte TAKSITNO { get; set; }
        public string FIYATTIPI { get; set; }
        public decimal SABITFIYAT { get; set; }
        public byte NETSISFTIPI { get; set; }
        public byte ISLEM { get; set; }
        public decimal TUTAR { get; set; }
        public string CARP { get; set; }
        public string NETLESTIR { get; set; }
        public byte ISKYER { get; set; }
    
        public virtual MGKOSULDETAY MGKOSULDETAY { get; set; }
    }
}
