//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGODEMEPLANI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MGODEMEPLANI()
        {
            this.MGODEMEPLANIDETAY = new HashSet<MGODEMEPLANIDETAY>();
        }
    
        public int ODEMEPLANID { get; set; }
        public string CARIKODU { get; set; }
        public System.DateTime SATISTARIHI { get; set; }
        public string FATURANO { get; set; }
        public decimal ONCEKIBORC { get; set; }
        public decimal BUGUNALINAN { get; set; }
        public decimal BUGUNODENEN { get; set; }
        public decimal PESINAT { get; set; }
        public byte TAKSITSAYISI { get; set; }
        public byte HESAPKESIM { get; set; }
        public string KASAKODU { get; set; }
        public int SUBEKODU { get; set; }
        public decimal HESAPLANANPESINAT { get; set; }
        public string BELGETIPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGODEMEPLANIDETAY> MGODEMEPLANIDETAY { get; set; }
    }
}
