//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGODEMEISKONTO
    {
        public int ODEMEID { get; set; }
        public byte TAKSITNO { get; set; }
        public decimal ISKORAN { get; set; }
        public byte ISKYER { get; set; }
    
        public virtual MGODEME MGODEME { get; set; }
    }
}
