//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGODEMEHESAP
    {
        public string KASAKODU { get; set; }
        public int ODEMEID { get; set; }
        public string HESAP_KODU { get; set; }
        public string INSERTKASA { get; set; }
    
        public virtual MGODEME MGODEME { get; set; }
        public virtual MGPARAM MGPARAM { get; set; }
    }
}
