//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGYAZICI
    {
        public int SUBE { get; set; }
        public string KASA { get; set; }
        public int FATYAZICI { get; set; }
        public int EKSYAZICI { get; set; }
        public int SOZYAZICI { get; set; }
        public string FATYADI { get; set; }
        public string EKSYADI { get; set; }
        public string SOZYADI { get; set; }
        public string EKSDIZAYNKODU { get; set; }
        public Nullable<int> RAPYAZICI { get; set; }
        public string RAPYADI { get; set; }
        public Nullable<int> REYONYAZICI { get; set; }
        public string REYONYADI { get; set; }
        public Nullable<int> IRSYAZICI { get; set; }
        public string IRSYADI { get; set; }
        public Nullable<int> SIPYAZICI { get; set; }
        public string SIPYADI { get; set; }
        public Nullable<byte> MODULNO { get; set; }
        public Nullable<int> IADEYAZICI { get; set; }
        public string IADEYADI { get; set; }
        public int FATDIZAYNNO { get; set; }
        public int IRSDIZAYNNO { get; set; }
        public int SIPDIZAYNNO { get; set; }
        public int SENETTAHDIZAYNNO { get; set; }
    }
}
