//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSA_SITE_STOKTEKNIKTANIM
    {
        public int ID { get; set; }
        public Nullable<int> STOK_ID { get; set; }
        public Nullable<int> TEKNIK_TANIM_ID { get; set; }
        public string DEGER { get; set; }
        public string STOK_KODU { get; set; }
        public string AKTIF { get; set; }
    }
}
