//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSA_SITE_MODELLER
    {
        public int ID { get; set; }
        public string URETICI { get; set; }
        public string MODEL_ADI { get; set; }
        public string ARAC { get; set; }
        public string BAS_YIL { get; set; }
        public string BIT_YIL { get; set; }
        public string DURUM { get; set; }
    }
}
