//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSA_TBLISEMRI
    {
        public int ISEMRINO { get; set; }
        public string STOK_KODU { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string TEKNIK_RESIM_NO { get; set; }
        public string SIPNO { get; set; }
        public Nullable<System.DateTime> TES_TAR { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public string KAYIT_YAPAN { get; set; }
        public Nullable<System.DateTime> DUZELTME_TARIHI { get; set; }
        public string DUZELTME_YAPAN { get; set; }
    }
}
