//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAPPRIGHTS
    {
        public int USERID { get; set; }
        public string APPNAME { get; set; }
        public string FIX { get; set; }
        public string VISIBLE { get; set; }
        public string PROGID { get; set; }
        public string RIGHTS { get; set; }
    }
}
