//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBNKLOGTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBNKLOGTRA()
        {
            this.TBLBNKISKONTOKREDI = new HashSet<TBLBNKISKONTOKREDI>();
        }
    
        public string BA { get; set; }
        public Nullable<byte> ISLEMTIPI { get; set; }
        public string REFERANSNO { get; set; }
        public Nullable<byte> YERTIPI { get; set; }
        public string TERSKAYIT { get; set; }
        public string TERSREFERANSNO { get; set; }
        public string NETHESKODU { get; set; }
        public string KARSIHESKOD { get; set; }
        public string KARSIBANKAKODU { get; set; }
        public string KARSISUBEKODU { get; set; }
        public string KARSIBANKAHESNO { get; set; }
        public string DEKONTNO { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<byte> DOVIZTIPI { get; set; }
        public Nullable<decimal> DOVIZTUTAR { get; set; }
        public Nullable<byte> KARSIDOVIZTIPI { get; set; }
        public Nullable<decimal> KARSIDOVIZTUTAR { get; set; }
        public string GELGIDBA { get; set; }
        public string GELGIDMUHKODU { get; set; }
        public Nullable<decimal> GELGIDTUTAR { get; set; }
        public Nullable<byte> GELGIDDOVIZTIPI { get; set; }
        public Nullable<decimal> GELGIDDOVIZTUTAR { get; set; }
        public string GELGIDNETHESKODU { get; set; }
        public string GELGIDPROJEKODU { get; set; }
        public string GELGIDMUHREFKOD { get; set; }
        public string VERGIBA1 { get; set; }
        public string VERGIMUHKODU1 { get; set; }
        public Nullable<decimal> VERGITUTAR1 { get; set; }
        public Nullable<byte> VERGIDOVIZTIPI1 { get; set; }
        public Nullable<decimal> VERGIDOVIZTUTAR1 { get; set; }
        public string VERGINETHESKODU1 { get; set; }
        public string VERGIPROJEKODU1 { get; set; }
        public string VERGIMUHREFKOD1 { get; set; }
        public string VERGIBA2 { get; set; }
        public string VERGIMUHKODU2 { get; set; }
        public Nullable<decimal> VERGITUTAR2 { get; set; }
        public Nullable<byte> VERGIDOVIZTIPI2 { get; set; }
        public Nullable<decimal> VERGIDOVIZTUTAR2 { get; set; }
        public string VERGINETHESKODU2 { get; set; }
        public string VERGIPROJEKODU2 { get; set; }
        public string VERGIMUHREFKOD2 { get; set; }
        public string YEDMASBA1 { get; set; }
        public string YEDMASMUHKODU1 { get; set; }
        public Nullable<decimal> YEDMASTUTAR1 { get; set; }
        public Nullable<byte> YEDMASDOVIZTIPI1 { get; set; }
        public Nullable<decimal> YEDMASDOVIZTUTAR1 { get; set; }
        public string YEDMASNETHESKODU1 { get; set; }
        public string YEDMASPROJEKODU1 { get; set; }
        public string YEDMASMUHREFKOD1 { get; set; }
        public string YEDMASBA2 { get; set; }
        public string YEDMASMUHKODU2 { get; set; }
        public Nullable<decimal> YEDMASTUTAR2 { get; set; }
        public Nullable<byte> YEDMASDOVIZTIPI2 { get; set; }
        public Nullable<decimal> YEDMASDOVIZTUTAR2 { get; set; }
        public string YEDMASNETHESKODU2 { get; set; }
        public string YEDMASPROJEKODU2 { get; set; }
        public string YEDMASMUHREFKOD2 { get; set; }
        public short SUBE_KODU { get; set; }
        public Nullable<System.DateTime> BNKOPTARIH { get; set; }
        public Nullable<System.DateTime> VADETARIH { get; set; }
        public Nullable<System.DateTime> EFFEKTIFTARIH { get; set; }
        public Nullable<decimal> FAIZORAN { get; set; }
        public string ACIKLAMA { get; set; }
        public string KARSIACIKLAMA { get; set; }
        public string YEVACIKLAMA { get; set; }
        public string ENTEGREFKEY { get; set; }
        public string PROJEKODU { get; set; }
        public string PLASIYERKODU { get; set; }
        public string MUHREFKOD { get; set; }
        public Nullable<byte> HESAPTIPI { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<int> YEDEK3 { get; set; }
        public Nullable<int> YEDEK4 { get; set; }
        public Nullable<int> YEDEK5 { get; set; }
        public Nullable<int> YEDEK6 { get; set; }
        public Nullable<decimal> YEDEK7 { get; set; }
        public Nullable<decimal> YEDEK8 { get; set; }
        public Nullable<decimal> YEDEK9 { get; set; }
        public Nullable<decimal> YEDEK10 { get; set; }
        public Nullable<System.DateTime> YEDEK11 { get; set; }
        public Nullable<System.DateTime> YEDEK12 { get; set; }
        public Nullable<System.DateTime> YEDEK13 { get; set; }
        public Nullable<System.DateTime> YEDEK14 { get; set; }
        public string YEDEK15 { get; set; }
        public string YEDEK16 { get; set; }
        public string ONAYTIPI { get; set; }
        public int ONAYNUM { get; set; }
        public Nullable<byte> MASRAFTEKCOK { get; set; }
        public string KAYNAK { get; set; }
        public Nullable<decimal> LIBORORAN { get; set; }
        public Nullable<decimal> SPREADORAN { get; set; }
        public string IHRACAT { get; set; }
        public Nullable<byte> TAKSIT { get; set; }
        public Nullable<byte> DONEM { get; set; }
        public Nullable<decimal> TAKSITTUTAR { get; set; }
        public Nullable<decimal> TAKSITDOVTUTAR { get; set; }
        public Nullable<decimal> KALANTUTAR { get; set; }
        public Nullable<decimal> KALANDOVTUTAR { get; set; }
        public Nullable<byte> HANGITAKSIT { get; set; }
        public string KARSIIBANNO { get; set; }
        public string BASITFAIZKULLAN { get; set; }
        public string ODEPLAN { get; set; }
        public string FAIZVERGIDAHIL { get; set; }
        public string CEZABA { get; set; }
        public string CEZAMUHKODU { get; set; }
        public Nullable<decimal> CEZATUTAR { get; set; }
        public Nullable<byte> CEZADOVIZTIPI { get; set; }
        public Nullable<decimal> CEZADOVIZTUTAR { get; set; }
        public string CEZANETHESKODU { get; set; }
        public string CEZAPROJEKODU { get; set; }
        public string CEZAMUHREFKOD { get; set; }
        public Nullable<decimal> CEZAORANI { get; set; }
        public string ERKENKAPATILMIS { get; set; }
        public string ARAODEME { get; set; }
        public string KREDI_NO { get; set; }
        public string BELGE_TURU { get; set; }
        public string STOPAJBA { get; set; }
        public string STOPAJMUHKODU { get; set; }
        public Nullable<decimal> STOPAJTUTAR { get; set; }
        public Nullable<byte> STOPAJDOVIZTIPI { get; set; }
        public Nullable<decimal> STOPAJDOVIZTUTAR { get; set; }
        public string STOPAJNETHESKODU { get; set; }
        public string STOPAJPROJEKODU { get; set; }
        public string STOPAJMUHREFKOD { get; set; }
        public string VADEDENONCE { get; set; }
        public string GUNLUKKAZANVADEHESAP { get; set; }
        public string VADELIFAIZISLEMEKULLAN { get; set; }
        public string VADELIUSTLIMITKULLAN { get; set; }
        public Nullable<decimal> FAIZISLENMEYECEKBAKTUT { get; set; }
        public Nullable<decimal> VHESUSTLIMTUTAR { get; set; }
        public string UZUNVADEFARKLIHESAP { get; set; }
        public Nullable<byte> UZUNVADEDEGERTAKSIT { get; set; }
        public string UZUNVADEMUHKOD { get; set; }
    
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT { get; set; }
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT1 { get; set; }
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT2 { get; set; }
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT3 { get; set; }
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT4 { get; set; }
        public virtual TBLBNKHESSABIT TBLBNKHESSABIT5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKISKONTOKREDI> TBLBNKISKONTOKREDI { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
        public virtual TBLTCMBSUBESABIT TBLTCMBSUBESABIT { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
