//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBCK_MRPSIP_PLAN_BAGDATA
    {
        public string BCKNO { get; set; }
        public Nullable<int> INCKEYNO { get; set; }
        public short ISLETME_KODU { get; set; }
        public Nullable<int> MRPSIP_ID { get; set; }
        public Nullable<int> MRPPLAN_ID { get; set; }
        public string FABRIKA_KODU { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLURMSUBEDEPOFABRIKA TBLURMSUBEDEPOFABRIKA { get; set; }
    }
}
