//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBUTCEDONEMTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBUTCEDONEMTRA()
        {
            this.TBLBILESENDONEMDEGERTRA = new HashSet<TBLBILESENDONEMDEGERTRA>();
            this.TBLBUTCEBILANCODEGER = new HashSet<TBLBUTCEBILANCODEGER>();
            this.TBLBUTCEDONEMTRA1 = new HashSet<TBLBUTCEDONEMTRA>();
            this.TBLBUTCEDONEMTRA11 = new HashSet<TBLBUTCEDONEMTRA>();
            this.TBLBUTCEKURTAHMIN = new HashSet<TBLBUTCEKURTAHMIN>();
            this.TBLBUTCENAKITAKIM = new HashSet<TBLBUTCENAKITAKIM>();
        }
    
        public int INCKEYNO { get; set; }
        public int BUTCE_ID { get; set; }
        public System.DateTime BASLANGIC_TARIHI { get; set; }
        public System.DateTime BITIS_TARIHI { get; set; }
        public string DONEM_ISMI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> REFERANS_DONEM_ID { get; set; }
        public Nullable<int> DEVIR_DONEM_ID { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<short> I_YEDEK1 { get; set; }
        public Nullable<short> I_YEDEK2 { get; set; }
        public Nullable<short> I_YEDEK3 { get; set; }
        public Nullable<short> I_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK4 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK4 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBILESENDONEMDEGERTRA> TBLBILESENDONEMDEGERTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEBILANCODEGER> TBLBUTCEBILANCODEGER { get; set; }
        public virtual TBLBUTCEMAS TBLBUTCEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEDONEMTRA> TBLBUTCEDONEMTRA1 { get; set; }
        public virtual TBLBUTCEDONEMTRA TBLBUTCEDONEMTRA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEDONEMTRA> TBLBUTCEDONEMTRA11 { get; set; }
        public virtual TBLBUTCEDONEMTRA TBLBUTCEDONEMTRA3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEKURTAHMIN> TBLBUTCEKURTAHMIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCENAKITAKIM> TBLBUTCENAKITAKIM { get; set; }
    }
}
