//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCEKSENDEK
    {
        public short SUBE_KODU { get; set; }
        public int INCKEYNO { get; set; }
        public string SERI_NO { get; set; }
        public int DEKONT_NO { get; set; }
        public short DEKONT_PRGNO { get; set; }
        public byte CEKSENTIP { get; set; }
        public string FISNO { get; set; }
        public Nullable<System.DateTime> ISLEM_TARIHI { get; set; }
        public Nullable<decimal> DEKTUTAR { get; set; }
        public Nullable<byte> DEKDOVTIPI { get; set; }
        public Nullable<decimal> DEKDOVTUT { get; set; }
        public Nullable<decimal> DEKDOVKUR { get; set; }
        public Nullable<decimal> DEKKURFARKI { get; set; }
        public string TAHTEMHES_KOD { get; set; }
        public string GIDERHES_KOD { get; set; }
        public string VIRMANHES_KOD { get; set; }
        public string ALACAKCARI_KODU { get; set; }
        public string BORCCARI_KODU { get; set; }
        public Nullable<decimal> TAHSILMASRAFTUT { get; set; }
        public Nullable<decimal> BANKABORCBEDELI { get; set; }
        public Nullable<decimal> PROTMASRAFTUT { get; set; }
        public Nullable<decimal> GENGIDMASRAFTUT { get; set; }
        public string DEKONTACIK { get; set; }
        public string CARIACIK { get; set; }
        public string YEVMIYEACIK { get; set; }
        public string DEKPLASKODU { get; set; }
        public string DEKREFKODU { get; set; }
        public string CARIMUHASEBE { get; set; }
        public string BANKAKODU { get; set; }
        public string SC_NO { get; set; }
        public Nullable<System.DateTime> SC_CIKTRH { get; set; }
        public Nullable<System.DateTime> SC_ODETRH { get; set; }
        public string SC_VERILENK { get; set; }
        public string SC_BANKNO { get; set; }
        public string SC_SONDUR { get; set; }
        public string SC_YERI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> KURFARKI { get; set; }
        public string SC_ALB_NO { get; set; }
        public string SC_VERB_NO { get; set; }
        public string YERI { get; set; }
        public string TERSISLEM { get; set; }
        public string DEKPROJEKODU { get; set; }
        public string MASRAFAYRI { get; set; }
    
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
