//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARISK
    {
        public string CARIKOD { get; set; }
        public string RISKGRUP { get; set; }
        public Nullable<decimal> RISKLIMITI { get; set; }
        public Nullable<decimal> TEMINATI { get; set; }
        public Nullable<decimal> CARISK { get; set; }
        public Nullable<decimal> CCRISK { get; set; }
        public Nullable<decimal> SARISK { get; set; }
        public Nullable<decimal> SCRISK { get; set; }
        public Nullable<decimal> IRSRISK { get; set; }
        public Nullable<decimal> SIPRISK { get; set; }
        public Nullable<decimal> RISKLIMITIO { get; set; }
        public Nullable<decimal> TEMINATIO { get; set; }
        public Nullable<decimal> CARISKO { get; set; }
        public Nullable<decimal> CCRISKO { get; set; }
        public Nullable<decimal> SARISKO { get; set; }
        public Nullable<decimal> SCRISKO { get; set; }
        public Nullable<decimal> IRSRISKO { get; set; }
        public Nullable<decimal> SIPRISKO { get; set; }
        public Nullable<decimal> BORCRISKO { get; set; }
        public Nullable<byte> SIPRISKDAVRAN { get; set; }
        public Nullable<byte> IRSRISKDAVRAN { get; set; }
        public Nullable<byte> FATRISKDAVRAN { get; set; }
        public string DOVIZLI { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public Nullable<decimal> YED1RISK { get; set; }
        public Nullable<decimal> YED2RISK { get; set; }
        public Nullable<decimal> YED1POZIT { get; set; }
        public Nullable<decimal> YED2POZIT { get; set; }
        public Nullable<decimal> YED1RISKO { get; set; }
        public Nullable<decimal> YED2RISKO { get; set; }
        public Nullable<decimal> YED1POZITO { get; set; }
        public Nullable<decimal> YED2POZITO { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<byte> INT_YEDEK1 { get; set; }
        public Nullable<byte> YUKRISKDAVRAN { get; set; }
        public Nullable<byte> SEVKRISKDAVRAN { get; set; }
        public Nullable<decimal> YUKRISKO { get; set; }
        public Nullable<decimal> SEVKRISKO { get; set; }
        public Nullable<decimal> YUKRISK { get; set; }
        public Nullable<decimal> SEVKRISK { get; set; }
        public string ONAYTIPI { get; set; }
        public Nullable<int> ONAYNUM { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
    }
}
