//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCRMEXCHANGEPRM
    {
        public int INCKEYNO { get; set; }
        public short SUBE_KODU { get; set; }
        public short NETKULID { get; set; }
        public string URL { get; set; }
        public string DOMAIN { get; set; }
        public string KULLANICI { get; set; }
        public string SIFRE { get; set; }
        public string KOKDIZIN { get; set; }
        public string GOREVTIPLERI { get; set; }
        public string TAKVIMTIPLERI { get; set; }
        public string CRMKAYITLARI { get; set; }
        public string EWSKAYITLARI { get; set; }
        public string TAKVIM_ONSATAKTTIPI { get; set; }
        public string GOREV_ONSATAKTTIPI { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public string C_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
    
        public virtual TBLKULLANP TBLKULLANP { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
