//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCIZELGETASLAK
    {
        public int INCKEYNO { get; set; }
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string SD_TASLAK_KODU { get; set; }
        public Nullable<System.DateTime> SD_TASLAK_TARIH { get; set; }
        public string SD_MODEL_PATH { get; set; }
        public Nullable<System.DateTime> SD_STARTDATE { get; set; }
        public Nullable<System.DateTime> SD_END_DATE { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public Nullable<System.DateTime> PO_DELIVERY_DATE { get; set; }
        public string PO_ITEM_CODE { get; set; }
        public string PO_NUMBER { get; set; }
        public Nullable<int> PO_PRIORITY { get; set; }
        public Nullable<decimal> PO_QUANTITY { get; set; }
        public string PO_REF_PROD_NO { get; set; }
        public string PO_SIPNO { get; set; }
        public Nullable<int> PO_SIPKONT { get; set; }
        public string JO_CODE { get; set; }
        public Nullable<decimal> JO_QUANTITY { get; set; }
        public Nullable<int> JO_JOB_INDEX { get; set; }
        public Nullable<decimal> JO_TIME_SECOND { get; set; }
        public Nullable<int> SI_MACHINE_ID { get; set; }
        public Nullable<System.DateTime> SI_START_DATE { get; set; }
        public Nullable<System.DateTime> SI_END_DATE { get; set; }
        public Nullable<decimal> SI_OPERATION_QUANTITY { get; set; }
        public Nullable<int> SI_SCHEDULE_TYPE { get; set; }
        public string SI_CONTINUEDJOBSCHEDULEINFO { get; set; }
        public Nullable<int> PR_KAYNAK_ID { get; set; }
        public Nullable<decimal> PR_COUNT { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK4 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK4 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string SD_AKTIF_TASLAK { get; set; }
        public string PO_ITEM_YAPKOD { get; set; }
        public string SI_STATION_CODE { get; set; }
        public string TASLAK_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> JO_DUEDATE { get; set; }
        public Nullable<decimal> PO_BALANCEQUANTITY { get; set; }
        public Nullable<System.DateTime> PO_SIPTESTAR { get; set; }
        public string PO_OPRLIMIT { get; set; }
        public Nullable<System.DateTime> PO_CLC_DELIVERYDATE { get; set; }
        public string PO_CUSTOMERCODE { get; set; }
        public string FABRIKA_KODU { get; set; }
        public Nullable<short> PR_SETNO { get; set; }
        public Nullable<System.DateTime> PO_RELEASEDATE { get; set; }
        public Nullable<decimal> PR_LIFETIME_CONSUMPTION { get; set; }
        public string PO_TOPPROD_CODE { get; set; }
        public string PO_TOPPROD_CONFIGCODE { get; set; }
        public string PO_SIP_KESINPLAN { get; set; }
        public Nullable<decimal> PO_SIP_STHAR_GCMIK { get; set; }
        public string IS_SCHEDULED { get; set; }
        public string UNSCHEDULE_DESCRIPTION { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        public virtual TBLURMSUBEDEPOFABRIKA TBLURMSUBEDEPOFABRIKA { get; set; }
    }
}
