//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONFIGMASEK
    {
        public int EKCONFIGMAS_ID { get; set; }
    
        public virtual TBLCONFIGMAS TBLCONFIGMAS { get; set; }
    }
}
