//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCRMADAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCRMADAY()
        {
            this.TBLCRMADAYURUN = new HashSet<TBLCRMADAYURUN>();
            this.TBLCRMADAYURUNGRUP = new HashSet<TBLCRMADAYURUNGRUP>();
            this.TBLCRMFIRSAT = new HashSet<TBLCRMFIRSAT>();
        }
    
        public string ADAYKOD { get; set; }
        public short SUBE_KODU { get; set; }
        public string CARI_KOD { get; set; }
        public string PAZAKTKOD { get; set; }
        public string CRMKULKOD { get; set; }
        public Nullable<short> SATASAMAKOD { get; set; }
        public string KAYIPNEDENKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> OLASILIK { get; set; }
        public Nullable<decimal> SATISDEGER { get; set; }
        public Nullable<byte> DOVIZTIPI { get; set; }
        public Nullable<decimal> DOVSATISDEGER { get; set; }
        public Nullable<System.DateTime> KAPANISTARIHI { get; set; }
        public string GIZLI { get; set; }
        public string KAYITDEGTIP { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> DURUMTARIHI { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> L_YEDEK1 { get; set; }
        public Nullable<int> L_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
    
        public virtual TBLCARIEMAIL TBLCARIEMAIL { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        public virtual TBLCRMSATASAMASI TBLCRMSATASAMASI { get; set; }
        public virtual TBLCRMKAYIPNEDEN TBLCRMKAYIPNEDEN { get; set; }
        public virtual TBLCRMPAZAKT TBLCRMPAZAKT { get; set; }
        public virtual TBLCRMKULLANP TBLCRMKULLANP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMADAYURUN> TBLCRMADAYURUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMADAYURUNGRUP> TBLCRMADAYURUNGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMFIRSAT> TBLCRMFIRSAT { get; set; }
    }
}
