//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDAGITIM
    {
        public short ISLETME_KODU { get; set; }
        public int ISLEMSIRANO { get; set; }
        public string KAYNAKKODU { get; set; }
        public string KAYNAKREFKOD { get; set; }
        public string KAYNAKPROJE { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string DAGITIMKODU { get; set; }
        public string DAGITIMREFKOD { get; set; }
        public string DAGITIMPROJE { get; set; }
        public string ALACAKKODU { get; set; }
        public string ALACAKREFKOD { get; set; }
        public string ALACAKPROJE { get; set; }
        public string FISNO { get; set; }
        public string ACIKLAMA { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string MIKTARGETIRSQL { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLMUPLAN TBLMUPLAN { get; set; }
        public virtual TBLMUPLAN TBLMUPLAN1 { get; set; }
        public virtual TBLMUPLAN TBLMUPLAN2 { get; set; }
    }
}
