//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDEPOKILIT_MAPPING
    {
        public int ISLEM_TIPI { get; set; }
        public int ISLEM_KULLDILKODU { get; set; }
        public string TABLO_ISMI { get; set; }
        public string DEPO_KOLONADI { get; set; }
        public string STOK_KOLONADI { get; set; }
        public string KISIT_KOLON1 { get; set; }
        public string KISIT_KOLON1_VERITIP { get; set; }
        public string KISIT1 { get; set; }
        public string KISIT_KOLON2 { get; set; }
        public string KISIT_KOLON2_VERITIP { get; set; }
        public string KISIT2 { get; set; }
        public string KISIT_KOLON3 { get; set; }
        public string KISIT_KOLON3_VERITIP { get; set; }
        public string KISIT3 { get; set; }
        public string KISIT_KOLON4 { get; set; }
        public string KISIT_KOLON4_VERITIP { get; set; }
        public string KISIT4 { get; set; }
        public string KISIT_KOLON5 { get; set; }
        public string KISIT_KOLON5_VERITIP { get; set; }
        public string KISIT5 { get; set; }
        public string KISIT_KOLON6 { get; set; }
        public string KISIT_KOLON6_VERITIP { get; set; }
        public string KISIT6 { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
    }
}
