//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDAMGAVERGISI
    {
        public short SUBE_KODU { get; set; }
        public int INCKEYNO { get; set; }
        public short YIL { get; set; }
        public string SIRANO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SOZCARIKOD { get; set; }
        public string SOZUNVAN { get; set; }
        public string SOZKODU { get; set; }
        public Nullable<decimal> MASRAF { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> DVORAN { get; set; }
        public Nullable<decimal> DVTUTAR { get; set; }
        public Nullable<decimal> MATRAH { get; set; }
        public string MUHKOD { get; set; }
        public string REFKOD { get; set; }
        public string PROJEKODU { get; set; }
        public Nullable<byte> DOVTIP { get; set; }
        public Nullable<decimal> DOVMATRAH { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK5 { get; set; }
        public Nullable<decimal> F_YEDEK6 { get; set; }
        public Nullable<System.DateTime> D_YEDEK7 { get; set; }
        public Nullable<System.DateTime> D_YEDEK8 { get; set; }
        public string V_YEDEK10 { get; set; }
        public string V_YEDEK11 { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLDAMGASOZ TBLDAMGASOZ { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
    }
}
