//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLESNOZFIY
    {
        public int INCKEYNO { get; set; }
        public string STOK_KODU { get; set; }
        public string A_S { get; set; }
        public System.DateTime BASTAR { get; set; }
        public Nullable<System.DateTime> BITTAR { get; set; }
        public string FIYATGRUBU { get; set; }
        public Nullable<byte> FIYATDOVIZTIPI { get; set; }
        public Nullable<decimal> FIYAT1 { get; set; }
        public Nullable<decimal> FIYAT2 { get; set; }
        public Nullable<decimal> FIYAT3 { get; set; }
        public Nullable<decimal> FIYAT4 { get; set; }
        public string OZMASKOD { get; set; }
        public string OZTRADEGKOD { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> L_YEDEK1 { get; set; }
        public Nullable<int> L_YEDEK2 { get; set; }
        public Nullable<int> L_YEDEK3 { get; set; }
        public Nullable<int> L_YEDEK4 { get; set; }
        public Nullable<int> F_YEDEK1 { get; set; }
        public Nullable<int> F_YEDEK2 { get; set; }
        public Nullable<int> F_YEDEK3 { get; set; }
        public Nullable<int> F_YEDEK4 { get; set; }
        public Nullable<int> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK4 { get; set; }
        public string FIYATLISTKOD { get; set; }
    
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
        public virtual TBLESNOZMAS TBLESNOZMAS { get; set; }
        public virtual TBLESNOZTRA TBLESNOZTRA { get; set; }
    }
}
