//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMUSTAHSIL
    {
        public int INCKEYNO { get; set; }
        public short SUBE_KODU { get; set; }
        public string GIB_FATIRS_NO { get; set; }
        public string FTIRSIP { get; set; }
        public byte TIP { get; set; }
        public string FATIRS_NO { get; set; }
        public string CARI_KODU { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<System.DateTime> GUNCELLEMETARIHI { get; set; }
        public byte[] XMLBYTES { get; set; }
        public byte DURUM { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string UUID { get; set; }
        public Nullable<int> RESPONSECODE { get; set; }
        public string RESPONSEDESC { get; set; }
        public Nullable<int> EARSIVID { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<int> YEDEK3 { get; set; }
        public Nullable<int> YEDEK4 { get; set; }
        public Nullable<double> YEDEK5 { get; set; }
        public Nullable<double> YEDEK6 { get; set; }
        public Nullable<System.DateTime> YEDEK7 { get; set; }
        public Nullable<System.DateTime> YEDEK8 { get; set; }
        public string YEDEK9 { get; set; }
        public string YEDEK10 { get; set; }
        public string YEDEK11 { get; set; }
        public string YEDEK12 { get; set; }
    
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
