//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEIRSEK
    {
        public string GIB_FATIRS_NO { get; set; }
        public string LICENSEPLATEID { get; set; }
        public string CARRIERVKN { get; set; }
        public string CARRIERNAME { get; set; }
        public string CARRIERSUBCITY { get; set; }
        public string CARRIERCITY { get; set; }
        public string CARRIERCOUNTRY { get; set; }
        public string CARRIERPOSTAL { get; set; }
        public string DPERSON1FIRSTNAME { get; set; }
        public string DPERSON1FAMILYNAME { get; set; }
        public string DPERSON1TITLE { get; set; }
        public string DPERSON1NID { get; set; }
        public string DPERSON2FIRSTNAME { get; set; }
        public string DPERSON2FAMILYNAME { get; set; }
        public string DPERSON2TITLE { get; set; }
        public string DPERSON2NID { get; set; }
        public string DPERSON3FIRSTNAME { get; set; }
        public string DPERSON3FAMILYNAME { get; set; }
        public string DPERSON3TITLE { get; set; }
        public string DPERSON3NID { get; set; }
        public Nullable<System.DateTime> SEVKTAR { get; set; }
        public string DORSEPLAKA1 { get; set; }
        public string DORSEPLAKA2 { get; set; }
        public string DORSEPLAKA3 { get; set; }
        public Nullable<short> MATBUKULLANILSIN { get; set; }
        public string MATBUNO { get; set; }
        public Nullable<System.DateTime> MATBUTARIH { get; set; }
        public string FATIRS_NO { get; set; }
    }
}
