//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEVRAK
    {
        public int KAYITNO { get; set; }
        public byte TABLOTIPI { get; set; }
        public string KOD { get; set; }
        public Nullable<byte> EVRAKTIPI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> KAYITTAR { get; set; }
        public Nullable<System.DateTime> DUZELTTAR { get; set; }
        public Nullable<int> KULID { get; set; }
        public string DOSYAADI { get; set; }
        public int BILGIBOYUT { get; set; }
        public byte[] BILGI { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> EVRAKGRUPID { get; set; }
        public short STORAGETYPE { get; set; }
        public string FILETYPE { get; set; }
        public string EVRAKPATH { get; set; }
        public string EVRAKEDITPATH { get; set; }
        public Nullable<int> DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> EVRAKTARIHI { get; set; }
        public string EVRAKGUID { get; set; }
    }
}
