//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEPOSTALOG
    {
        public short SUBE_KODU { get; set; }
        public int SIRANO { get; set; }
        public System.DateTime TARIH { get; set; }
        public int MODNO { get; set; }
        public int PRGNO { get; set; }
        public string KIMDEN { get; set; }
        public string KIME { get; set; }
        public string KOPYA { get; set; }
        public string KONU { get; set; }
        public string MESAJ { get; set; }
        public string DOSYALAR { get; set; }
        public string GONDERIMDURUM { get; set; }
        public string HATA { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
