//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATKALEMILISKI
    {
        public int INCKEYNO { get; set; }
        public string KALEMYERI { get; set; }
        public int SATIRINCKEYNO { get; set; }
        public Nullable<int> KOSULINCKEYNO { get; set; }
        public Nullable<int> RELINCKEYNO { get; set; }
        public string TIP { get; set; }
        public string UPDATE_KODU { get; set; }
        public string ANAHTAR { get; set; }
    }
}
