//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFAIZORAN
    {
        public short ISLETME_KODU { get; set; }
        public byte SINIRAY { get; set; }
        public Nullable<decimal> FAIZ { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<short> YEDEK3 { get; set; }
        public Nullable<decimal> YEDEK4 { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
    }
}
