//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFARKLITESLIM
    {
        public int TARTIM_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string IRSALIYE_NO { get; set; }
        public string CARI_KOD { get; set; }
        public string STOK_KODU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string SIPARIS_NO { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLTARTIMBLG TBLTARTIMBLG { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
    }
}
