//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATUISK
    {
        public short SUBE_KODU { get; set; }
        public string OZELKOD2DEGERI { get; set; }
        public string ALIS_HES_KOD_1 { get; set; }
        public string ALIS_HES_KOD_2 { get; set; }
        public string ALIS_HES_KOD_3 { get; set; }
        public string ALIS_HES_KOD_4 { get; set; }
        public string ALIS_HES_KOD_5 { get; set; }
        public string VERISK_HES_KOD_1 { get; set; }
        public string VERISK_HES_KOD_2 { get; set; }
        public string VERISK_HES_KOD_3 { get; set; }
        public string VERISK_HES_KOD_4 { get; set; }
        public string VERISK_HES_KOD_5 { get; set; }
    
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
