//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIHRMASRAFDEKONT
    {
        public int INCKEYNO { get; set; }
        public string SERI_NO { get; set; }
        public int DEKONT_NO { get; set; }
        public string CARI_KODU { get; set; }
        public string MASRAFKOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> VADE_TARIHI { get; set; }
        public Nullable<int> DOV_TIP { get; set; }
        public Nullable<decimal> DOV_TUT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> KDV { get; set; }
        public string FATIRSNO { get; set; }
        public string MAKBUZNO { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string BFORMCARI_KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string PROJE_KODU { get; set; }
        public string REFERANS { get; set; }
        public string EXPORTREFNO { get; set; }
        public short SUBE_KODU { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string BELGE_TIPI { get; set; }
        public string TEV_KOD { get; set; }
        public Nullable<decimal> TEV_ORAN { get; set; }
        public Nullable<decimal> TEV_TUTAR { get; set; }
        public string TEV_HESAP_KODU { get; set; }
        public Nullable<decimal> STOPAJ_TUTAR { get; set; }
        public Nullable<decimal> SSDF_TUTAR { get; set; }
    
        public virtual TBLIHRMASRAFTIP TBLIHRMASRAFTIP { get; set; }
    }
}
