//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLISEMRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLISEMRI()
        {
            this.TBLISEMRIREC = new HashSet<TBLISEMRIREC>();
            this.TBLISEMRIREZERVESTOK = new HashSet<TBLISEMRIREZERVESTOK>();
            this.TBLMRPSIPBAGLANTI = new HashSet<TBLMRPSIPBAGLANTI>();
            this.TBLUAKMAS = new HashSet<TBLUAKMAS>();
        }
    
        public string ISEMRINO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string STOK_KODU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public System.DateTime TESLIM_TARIHI { get; set; }
        public string SIPARIS_NO { get; set; }
        public string KAPALI { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public string YEDEK3 { get; set; }
        public string YEDEK4 { get; set; }
        public Nullable<decimal> YEDEK5 { get; set; }
        public string PROJE_KODU { get; set; }
        public string REVNO { get; set; }
        public Nullable<int> ONCELIK { get; set; }
        public string REFISEMRINO { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string YAPKOD { get; set; }
        public Nullable<short> SIPKONT { get; set; }
        public string TEPEMAM { get; set; }
        public string TEPEYAPKOD { get; set; }
        public Nullable<System.DateTime> TEPETARIH { get; set; }
        public Nullable<System.DateTime> CALISMAZAMANI { get; set; }
        public string TEPESIPNO { get; set; }
        public Nullable<short> TEPESIPKONT { get; set; }
        public string ONAYTIPI { get; set; }
        public Nullable<int> ONAYNUM { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string REWORK { get; set; }
        public Nullable<short> DEPO_KODU { get; set; }
        public string SERINO { get; set; }
        public string FASONCARI { get; set; }
        public Nullable<short> CIKIS_DEPO_KODU { get; set; }
        public string ASORTIKOD { get; set; }
        public Nullable<int> ISEMRI_SIRA { get; set; }
        public string USK_STATUS { get; set; }
        public string REZERVASYON_STATUS { get; set; }
        public Nullable<int> SIRA_ONCELIK { get; set; }
        public Nullable<int> USTISEMRI_ID { get; set; }
        public Nullable<System.DateTime> BASLAYABILECEGI_TARIH { get; set; }
        public string SERINO2 { get; set; }
        public string HAT_KODU { get; set; }
    
        public virtual TBLASORTIMAS TBLASORTIMAS { get; set; }
        public virtual TBLESNYAPMAS TBLESNYAPMAS { get; set; }
        public virtual TBLESNYAPMAS TBLESNYAPMAS1 { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
        public virtual TBLUSTISEMRI TBLUSTISEMRI { get; set; }
        public virtual TBLURETHAT TBLURETHAT { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT1 { get; set; }
        public virtual TBLISEMRIEK TBLISEMRIEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISEMRIREC> TBLISEMRIREC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISEMRIREZERVESTOK> TBLISEMRIREZERVESTOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPSIPBAGLANTI> TBLMRPSIPBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUAKMAS> TBLUAKMAS { get; set; }
    }
}
