//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIHRGUMRUKBEYANNAME
    {
        public string DOSYANO { get; set; }
        public string GB_NUMARA { get; set; }
        public string GUMRUK_KODU { get; set; }
        public string GUMRUKCU_KODU { get; set; }
        public Nullable<System.DateTime> GB_TARIHI { get; set; }
        public Nullable<System.DateTime> GB_INTAC_TARIHI { get; set; }
        public Nullable<System.DateTime> GB_GELIS_TARIHI { get; set; }
        public string ATR_NO { get; set; }
        public string EUR1_NO { get; set; }
        public string FORM_A_NO { get; set; }
        public string MENSE_SERT_NO { get; set; }
        public string IMALATCI { get; set; }
        public string IHRACATCI { get; set; }
        public string ETIKETTIP { get; set; }
        public string ETIKETVAR { get; set; }
        public Nullable<System.DateTime> TEV_TARIHI { get; set; }
        public string TEVODENDI { get; set; }
        public Nullable<short> TESLIMSEKLI { get; set; }
        public Nullable<decimal> GB_KUR { get; set; }
        public string GB_ODEMETIP { get; set; }
        public short SUBE_KODU { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string KATI_GB_NO { get; set; }
        public Nullable<System.DateTime> KATI_GB_TARIH { get; set; }
        public string PARCALI_DOSYANO { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLIHRDOSYAMAS TBLIHRDOSYAMAS { get; set; }
        public virtual TBLIHRGUMRUKMAS TBLIHRGUMRUKMAS { get; set; }
    }
}
