//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASAMAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKASAMAS()
        {
            this.TBLKASA = new HashSet<TBLKASA>();
            this.TBLKASANUM = new HashSet<TBLKASANUM>();
        }
    
        public string KSMAS_KOD { get; set; }
        public string KSMAS_NAME { get; set; }
        public string DOVIZLI { get; set; }
        public string MUH_KOD { get; set; }
        public Nullable<System.DateTime> KSSONDEV_D { get; set; }
        public Nullable<decimal> KSSONDEV_T { get; set; }
        public string KSMAKBUZ_BAS { get; set; }
        public string KS_DEFBAS_TIP { get; set; }
        public Nullable<byte> DOVIZTIPI { get; set; }
        public Nullable<byte> CEVRIMTIPI { get; set; }
        public string KURFARKIGELIRKODU { get; set; }
        public string KURFARKIGIDERKODU { get; set; }
        public Nullable<decimal> KSSONDEV_DOVIZ { get; set; }
        public short SUBE_KODU { get; set; }
        public string YEDEK { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASA> TBLKASA { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASANUM> TBLKASANUM { get; set; }
    }
}
