//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANP()
        {
            this.MGKULLANICIHAKLARI = new HashSet<MGKULLANICIHAKLARI>();
            this.MGKULLANICIISKONTO = new HashSet<MGKULLANICIISKONTO>();
            this.TBLBKMTALEPKONTROL = new HashSet<TBLBKMTALEPKONTROL>();
            this.TBLBUTCEBILESENROLTRA = new HashSet<TBLBUTCEBILESENROLTRA>();
            this.TBLBUTCEROLTRA = new HashSet<TBLBUTCEROLTRA>();
            this.TBLCRMANKCEVAPMAS = new HashSet<TBLCRMANKCEVAPMAS>();
            this.TBLCRMEXCHANGELOG = new HashSet<TBLCRMEXCHANGELOG>();
            this.TBLCRMEXCHANGEPRM = new HashSet<TBLCRMEXCHANGEPRM>();
            this.TBLCRMKULLANP = new HashSet<TBLCRMKULLANP>();
            this.TBLCRMPAZAKT = new HashSet<TBLCRMPAZAKT>();
            this.TBLCRMPAZALTAKT = new HashSet<TBLCRMPAZALTAKT>();
            this.TBLCRMSKYAKT = new HashSet<TBLCRMSKYAKT>();
            this.TBLCRMSKYSABIT = new HashSet<TBLCRMSKYSABIT>();
            this.TBLCRMSKYTEMSILCI = new HashSet<TBLCRMSKYTEMSILCI>();
            this.TBLCRMWIZARDDATA = new HashSet<TBLCRMWIZARDDATA>();
            this.TBLDZNBASIMLOG = new HashSet<TBLDZNBASIMLOG>();
            this.TBLEFATKISIT = new HashSet<TBLEFATKISIT>();
            this.TBLIMZALOG = new HashSet<TBLIMZALOG>();
            this.TBLKARGOKULLANICI = new HashSet<TBLKARGOKULLANICI>();
            this.TBLKOLONGUVENLIK = new HashSet<TBLKOLONGUVENLIK>();
            this.TBLKULHAKDEVIR = new HashSet<TBLKULHAKDEVIR>();
            this.TBLKULLANHAKP = new HashSet<TBLKULLANHAKP>();
            this.TBLRCPCONSUSERTRA = new HashSet<TBLRCPCONSUSERTRA>();
            this.TBLRCPMAS = new HashSet<TBLRCPMAS>();
            this.TBLREPORTCOMMENTS = new HashSet<TBLREPORTCOMMENTS>();
            this.TBLSATIRGUVENLIK = new HashSet<TBLSATIRGUVENLIK>();
            this.TBLMASRAFMAS = new HashSet<TBLMASRAFMAS>();
            this.TBLMRPDENGELEMESABLON = new HashSet<TBLMRPDENGELEMESABLON>();
            this.TBLMRPSIPEKRMAS = new HashSet<TBLMRPSIPEKRMAS>();
            this.TBLNFDMAS = new HashSet<TBLNFDMAS>();
            this.TBLNPMKULLAN = new HashSet<TBLNPMKULLAN>();
            this.TBLNPMLOG = new HashSet<TBLNPMLOG>();
            this.TBLNTFPOOL = new HashSet<TBLNTFPOOL>();
            this.TBLVIEWHAK = new HashSet<TBLVIEWHAK>();
            this.TBLWORKFLOWTRA = new HashSet<TBLWORKFLOWTRA>();
            this.TBLWORKPATHTRA = new HashSet<TBLWORKPATHTRA>();
        }
    
        public short SUBE_KODU { get; set; }
        public short KULLANICI_NO { get; set; }
        public string KULLANICI_ISIM { get; set; }
        public string ISIM_SOYAD { get; set; }
        public string SICIL_NO { get; set; }
        public string SIFRE { get; set; }
        public string SIFRE1 { get; set; }
        public string SIFRE2 { get; set; }
        public string SIFRE3 { get; set; }
        public string SIFRE4 { get; set; }
        public string SIFRE5 { get; set; }
        public string SIFRE6 { get; set; }
        public string SIFRE7 { get; set; }
        public string SIFRE8 { get; set; }
        public Nullable<System.DateTime> ENSON_SIFRETAR { get; set; }
        public Nullable<System.DateTime> ENSON_SIFRESAAT { get; set; }
        public Nullable<System.DateTime> ENSON_LOGINTAR { get; set; }
        public Nullable<System.DateTime> ENSON_LOGINSAAT { get; set; }
        public Nullable<byte> EXPPERIOD { get; set; }
        public Nullable<System.DateTime> MAX_SIFRE_TAR { get; set; }
        public Nullable<byte> CONNECTION { get; set; }
        public Nullable<byte> GSIZ_LOGIN_SAYISI { get; set; }
        public Nullable<System.DateTime> GSIZ_LOGIN_TARIHI { get; set; }
        public Nullable<System.DateTime> GSIZ_LOGIN_SAATI { get; set; }
        public Nullable<System.DateTime> KILIT_TARIHI { get; set; }
        public Nullable<System.DateTime> KILIT_ZAMANI { get; set; }
        public Nullable<System.DateTime> TRH_KILIT_BAS { get; set; }
        public Nullable<System.DateTime> TRH_KILIT_BIT { get; set; }
        public string SIFRE_DEGIS { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<byte> YEDEK3 { get; set; }
        public Nullable<short> YEDEK4 { get; set; }
        public Nullable<int> YEDEK5 { get; set; }
        public Nullable<System.DateTime> YEDEK6 { get; set; }
        public string EMAIL { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public Nullable<short> GRUPKODU { get; set; }
        public string ADMINMI { get; set; }
        public Nullable<int> KAYITRENGI { get; set; }
        public string XISYERI { get; set; }
        public Nullable<byte> FORCECARD { get; set; }
        public string CARDID { get; set; }
        public string CEPTEL { get; set; }
        public string YENIYONTEM { get; set; }
        public Nullable<int> SSOUSERID { get; set; }
        public int TRH_KILIT_GUNGECMIS { get; set; }
        public int TRH_KILIT_GUNGELECEK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGKULLANICIHAKLARI> MGKULLANICIHAKLARI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGKULLANICIISKONTO> MGKULLANICIISKONTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMTALEPKONTROL> TBLBKMTALEPKONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEBILESENROLTRA> TBLBUTCEBILESENROLTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEROLTRA> TBLBUTCEROLTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKCEVAPMAS> TBLCRMANKCEVAPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGELOG> TBLCRMEXCHANGELOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGEPRM> TBLCRMEXCHANGEPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMKULLANP> TBLCRMKULLANP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMPAZAKT> TBLCRMPAZAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMPAZALTAKT> TBLCRMPAZALTAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYAKT> TBLCRMSKYAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYSABIT> TBLCRMSKYSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYTEMSILCI> TBLCRMSKYTEMSILCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMWIZARDDATA> TBLCRMWIZARDDATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDZNBASIMLOG> TBLDZNBASIMLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEFATKISIT> TBLEFATKISIT { get; set; }
        public virtual TBLENETSEPET TBLENETSEPET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIMZALOG> TBLIMZALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKARGOKULLANICI> TBLKARGOKULLANICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKOLONGUVENLIK> TBLKOLONGUVENLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULHAKDEVIR> TBLKULHAKDEVIR { get; set; }
        public virtual TBLKULLANENET TBLKULLANENET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANHAKP> TBLKULLANHAKP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRCPCONSUSERTRA> TBLRCPCONSUSERTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRCPMAS> TBLRCPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREPORTCOMMENTS> TBLREPORTCOMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATIRGUVENLIK> TBLSATIRGUVENLIK { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMASRAFMAS> TBLMASRAFMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPDENGELEMESABLON> TBLMRPDENGELEMESABLON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPSIPEKRMAS> TBLMRPSIPEKRMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNFDMAS> TBLNFDMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNPMKULLAN> TBLNPMKULLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNPMLOG> TBLNPMLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNTFPOOL> TBLNTFPOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLVIEWHAK> TBLVIEWHAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLWORKFLOWTRA> TBLWORKFLOWTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLWORKPATHTRA> TBLWORKPATHTRA { get; set; }
    }
}
