//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKKCARISTOKMUAYENE
    {
        public Nullable<short> ISLETME_KODU { get; set; }
        public string CARIKODU { get; set; }
        public string STOKKODU { get; set; }
        public string DEPKODU { get; set; }
        public string MYNKODU { get; set; }
        public Nullable<System.DateTime> GECERLILIKTARIHI { get; set; }
        public string AKTIF { get; set; }
        public string ACIKLAMA { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public Nullable<decimal> PPMDEGER { get; set; }
        public string OPKODU { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLKKDEP TBLKKDEP { get; set; }
        public virtual TBLKKMYNTIP TBLKKMYNTIP { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
    }
}
