//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKAPASITE
    {
        public string MAMULKODU { get; set; }
        public string SIPNO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string ISTKODU { get; set; }
        public string TURU { get; set; }
        public string OPKODU { get; set; }
        public Nullable<decimal> OPMIK { get; set; }
        public Nullable<decimal> TOPSURE { get; set; }
        public string OPNO { get; set; }
        public string YAPKOD { get; set; }
    
        public virtual TBLESNYAPMAS TBLESNYAPMAS { get; set; }
        public virtual TBLOPERATIONS_KATALOG TBLOPERATIONS_KATALOG { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
    }
}
