//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUHTASAR_TABLO3
    {
        public byte AYKODU { get; set; }
        public string UNVAN_ADRES { get; set; }
        public string VERGI_DAIRESI_NO { get; set; }
        public string TUR { get; set; }
        public Nullable<decimal> MATRAH { get; set; }
        public Nullable<decimal> VERGI { get; set; }
        public Nullable<decimal> FON { get; set; }
    }
}
