//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUHASEBEKODLAR
    {
        public short ORAN { get; set; }
        public string MUHKOD { get; set; }
        public string KDV { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<byte> YEDEK3 { get; set; }
        public Nullable<decimal> YEDEK4 { get; set; }
    }
}
