//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMAGAZALAR
    {
        public short SUBEKODU { get; set; }
        public string ISIM { get; set; }
        public string CARIKOD { get; set; }
        public string CARIKOD2 { get; set; }
        public Nullable<short> DEPOKODU { get; set; }
        public string MUHKOD { get; set; }
        public string MUHKOD2 { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLCASABIT TBLCASABIT1 { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        public virtual TBLMUPLAN TBLMUPLAN { get; set; }
        public virtual TBLMUPLAN TBLMUPLAN1 { get; set; }
    }
}
