//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUHFIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUHFIS()
        {
            this.TBLMUHFISEK = new HashSet<TBLMUHFISEK>();
        }
    
        public byte AY_KODU { get; set; }
        public string FISNO { get; set; }
        public int SIRA { get; set; }
        public string HES_KOD { get; set; }
        public System.DateTime TARIH { get; set; }
        public string BA { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string REF_KOD { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<byte> DOVIZTIP { get; set; }
        public Nullable<decimal> DOVIZTUT { get; set; }
        public Nullable<byte> FIRMADOVTIP { get; set; }
        public Nullable<decimal> FIRMADOVTUT { get; set; }
        public string UPDATEKODU { get; set; }
        public Nullable<System.DateTime> EVRAKTARIHI { get; set; }
        public string HESAPISMI { get; set; }
        public string YONTEM { get; set; }
        public string ENTEGREFKEY { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public Nullable<decimal> YEDEK3 { get; set; }
        public Nullable<decimal> YEDEK4 { get; set; }
        public Nullable<short> YEDEK5 { get; set; }
        public Nullable<short> YEDEK6 { get; set; }
        public Nullable<int> YEDEK7 { get; set; }
        public string YEDEK8 { get; set; }
        public string YEDEK9 { get; set; }
        public Nullable<byte> YEDEK10 { get; set; }
        public Nullable<System.DateTime> YEDEK11 { get; set; }
        public string PROJE_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string SUBELI { get; set; }
        public Nullable<short> HARKONTROL { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string BFORMCARIKODU { get; set; }
        public string BFORMBELGENO { get; set; }
        public string GUID { get; set; }
        public Nullable<int> ISLEMSIRANO { get; set; }
        public string KAYITSEKLI { get; set; }
        public string MGECDK { get; set; }
        public Nullable<short> KULL_ID { get; set; }
        public string ISLEMTIPI { get; set; }
        public Nullable<int> EDEFTER_SIRA { get; set; }
        public string INDKDV { get; set; }
    
        public virtual TBLMUPLAN TBLMUPLAN { get; set; }
        public virtual TBLMUHMAS TBLMUHMAS { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHFISEK> TBLMUHFISEK { get; set; }
        public virtual TBLUFRSMUHVADE TBLUFRSMUHVADE { get; set; }
    }
}
