//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMRPKAPASITEDETAY
    {
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public Nullable<System.DateTime> MRPPLAN_TARIH { get; set; }
        public string MRPPLAN_SIPNO { get; set; }
        public Nullable<int> MRPPLAN_SIPKONT { get; set; }
        public Nullable<int> REQUIREMENTITEM_ID { get; set; }
        public Nullable<int> REQUIREMENTITEM_SIRANO { get; set; }
        public string REQUIREMENTITEM_MAMUL_KODU { get; set; }
        public string REQUIREMENTITEM_MAMUL_ADI { get; set; }
        public string REQUIREMENTITEM_MAMYAPKOD { get; set; }
        public string REQUIREMENTITEM_MAMYAPACIK { get; set; }
        public string REQUIREMENTITEM_MAMOLCUBR1 { get; set; }
        public Nullable<int> REQUIREMENTITEM_PERIOD { get; set; }
        public Nullable<int> REQUIREMENTITEM_YEAR { get; set; }
        public Nullable<int> REQUIREMENTITEM_PERIODTYPE { get; set; }
        public Nullable<decimal> REQUIREMENTITEM_MIKTAR { get; set; }
        public string REQUIREMENTITEM_URUNGRUBU { get; set; }
        public string REQUIREMENTITEM_GRUPKODU { get; set; }
        public string REQUIREMENTITEM_KOD1 { get; set; }
        public string REQUIREMENTITEM_KOD2 { get; set; }
        public string REQUIREMENTITEM_KOD3 { get; set; }
        public string REQUIREMENTITEM_KOD4 { get; set; }
        public string REQUIREMENTITEM_KOD5 { get; set; }
        public string REQUIREMENTITEM_URUNGRUBUACIK { get; set; }
        public string REQUIREMENTITEM_ITEMPROCESSED { get; set; }
        public string REQUIREMENTITEM_REVNO { get; set; }
        public Nullable<int> PERIODITEM_INDEX { get; set; }
        public Nullable<int> PERIODITEM_PERIODNO { get; set; }
        public Nullable<int> PERIODITEM_PERIODYEAR { get; set; }
        public Nullable<System.DateTime> PERIODITEM_STARTTIME { get; set; }
        public Nullable<System.DateTime> PERIODITEM_ENDTIME { get; set; }
        public Nullable<int> PERIODITEM_PERIODTYPE { get; set; }
        public Nullable<int> CENTER_ITEMCOUNT { get; set; }
        public string CENTER_DUMMYMACHINE { get; set; }
        public Nullable<int> CENTER_ITEMTYPE { get; set; }
        public string CENTER_ITEMID { get; set; }
        public string CENTER_ITEMNAME { get; set; }
        public string CENTER_STATIONID { get; set; }
        public string CENTER_STATIONNAME { get; set; }
        public Nullable<decimal> CONTAINER_TOTALCAPACITY { get; set; }
        public Nullable<decimal> CONTAINER_USEDCAPACITY { get; set; }
        public string ROTAOPERATION_OPKEYNO { get; set; }
        public string ROTAOPERATION_OPKODU { get; set; }
        public string ROTAOPERATION_OPGRUP { get; set; }
        public string ROTAOPERATION_OPNO { get; set; }
        public string ROTAOPERATION_MAKDEGER { get; set; }
        public Nullable<decimal> ROTAOPERATION_PRODUCTIONTIME { get; set; }
        public string ROTAOPERATION_TIMETYPE { get; set; }
        public Nullable<decimal> ROTAOPERATION_SETUPTIME { get; set; }
        public string ROTAOPERATION_SETUPTIMETYPE { get; set; }
        public string ROTAOPERATION_ISTKODU { get; set; }
        public string ROTAOPERATION_MAKID { get; set; }
        public Nullable<decimal> ROTAOPERATION_QTYTONEXTOP { get; set; }
        public Nullable<int> ROTAOPERATION_MAK_DEGER_TIPI { get; set; }
        public string ROTAOPERATION_ISEMRINO { get; set; }
        public Nullable<int> ROTAOPERATION_ALTRECNO { get; set; }
        public string ROTAOPERATION_REVNO { get; set; }
        public string CONTAINERITEM_STOCKCODE { get; set; }
        public string CONTAINERITEM_STOCKNAME { get; set; }
        public string CONTAINERITEM_YAPKOD { get; set; }
        public string CONTAINERITEM_YAPACIK { get; set; }
        public string CONTAINERITEM_HAMOLCUBR1 { get; set; }
        public string CONTAINERITEM_MAMCODE { get; set; }
        public string CONTAINERITEM_MAMYAPCODE { get; set; }
        public string CONTAINERITEM_MAMADI { get; set; }
        public string CONTAINERITEM_MAMYAPACIK { get; set; }
        public Nullable<int> CONTAINERITEM_ID { get; set; }
        public Nullable<int> CONTAINERITEM_COPPYNO { get; set; }
        public Nullable<decimal> CONTAINERITEM_TOTALQUANTITY { get; set; }
        public Nullable<decimal> CONTAINERITEM_QTYBEFOREDIVIDE { get; set; }
        public Nullable<decimal> CONTAINERITEM_USEDQUANTITY { get; set; }
        public Nullable<int> CONTAINERITEM_PERIODNO { get; set; }
        public Nullable<int> CONTAINERITEM_PERIODYEAR { get; set; }
        public Nullable<int> CONTAINERITEM_RAWPERIODNO { get; set; }
        public Nullable<int> CONTAINERITEM_RAWPERIODYEAR { get; set; }
        public Nullable<System.DateTime> CONTAINERITEM_HAZIROLMALITARIH { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public string C_YEDEK4 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string FABRIKA_KODU { get; set; }
        public Nullable<decimal> ROTAOPERATION_CYCLETIME { get; set; }
    }
}
