//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMALIPRM
    {
        public short ISLETME_KODU { get; set; }
        public string X151YAZ { get; set; }
        public Nullable<byte> SNO { get; set; }
        public string X151DETAY { get; set; }
        public string X151KOD { get; set; }
        public string X151DKOD { get; set; }
        public string X710DETAY { get; set; }
        public string X710KOD { get; set; }
        public string X710DKOD { get; set; }
        public string X711BENZER { get; set; }
        public string X711DETAY { get; set; }
        public string X711KOD { get; set; }
        public string X711DKOD { get; set; }
        public string BRIM_ORAN { get; set; }
        public string SADECE710 { get; set; }
        public string STOKMALIYET { get; set; }
        public Nullable<short> SDEPOKODU { get; set; }
        public string STOKMUHKOD { get; set; }
        public string MALGIDER_1 { get; set; }
        public string MALGIDER_2 { get; set; }
        public string MALGIDER_3 { get; set; }
        public string MALGIDER_4 { get; set; }
        public string MALGIDER_5 { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public string YEDEK3 { get; set; }
        public Nullable<byte> YEDEK4 { get; set; }
        public Nullable<byte> YEDEK5 { get; set; }
        public Nullable<short> YEDEK6 { get; set; }
        public Nullable<short> YEDEK7 { get; set; }
        public string YEDEK8 { get; set; }
        public string YEDEK9 { get; set; }
        public string YEDEK10 { get; set; }
        public string YEDEK11 { get; set; }
        public string YEDEK12 { get; set; }
        public string YEDEK13 { get; set; }
        public string YEDEK14 { get; set; }
        public string YEDEK15 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string HAT_BAZINDA_MALIYET { get; set; }
        public string SIPARIS_BAZINDA_MALIYET { get; set; }
        public string PROJE_BAZINDA_MALIYET { get; set; }
        public string YAPKOD_BAZINDA_MALIYET { get; set; }
        public string MALGIDER_6 { get; set; }
        public string MALGIDER_7 { get; set; }
        public string MALGIDER_8 { get; set; }
        public string MALGIDER_9 { get; set; }
        public string MALGIDER_10 { get; set; }
        public string MAHSUP_AYIN_SON_GUNU { get; set; }
        public string PROJE_BAZ_MAL_MAHSUBA_YANSIT { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
    }
}
