//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMALIANAGHAT
    {
        public short ISLETME_KODU { get; set; }
        public string ANAKOD { get; set; }
        public string HAT_KODU { get; set; }
        public string REFKOD { get; set; }
        public string ISCI1KOD { get; set; }
        public string ISCI2KOD { get; set; }
        public string ENERJI1KOD { get; set; }
        public string ENERJI2KOD { get; set; }
        public string AMORTISMAN1KOD { get; set; }
        public string AMORTISMAN2KOD { get; set; }
        public string YARDSER1KOD { get; set; }
        public string YARDSER2KOD { get; set; }
        public string YEDPARCA1KOD { get; set; }
        public string YEDPARCA2KOD { get; set; }
        public string MALGIDER1_1KOD { get; set; }
        public string MALGIDER1_2KOD { get; set; }
        public string MALGIDER2_1KOD { get; set; }
        public string MALGIDER2_2KOD { get; set; }
        public string MALGIDER3_1KOD { get; set; }
        public string MALGIDER3_2KOD { get; set; }
        public string MALGIDER4_1KOD { get; set; }
        public string MALGIDER4_2KOD { get; set; }
        public string MALGIDER5_1KOD { get; set; }
        public string MALGIDER5_2KOD { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<short> I_YEDEK1 { get; set; }
        public Nullable<short> I_YEDEK2 { get; set; }
        public Nullable<byte> B_YEDEK1 { get; set; }
        public Nullable<byte> B_YEDEK2 { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string MALGIDER6_1KOD { get; set; }
        public string MALGIDER6_2KOD { get; set; }
        public string MALGIDER7_1KOD { get; set; }
        public string MALGIDER7_2KOD { get; set; }
        public string MALGIDER8_1KOD { get; set; }
        public string MALGIDER8_2KOD { get; set; }
        public string MALGIDER9_1KOD { get; set; }
        public string MALGIDER9_2KOD { get; set; }
        public string MALGIDER10_1KOD { get; set; }
        public string MALGIDER10_2KOD { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLMALIANAG TBLMALIANAG { get; set; }
        public virtual TBLURETHAT TBLURETHAT { get; set; }
    }
}
