//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMAKBKM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMAKBKM()
        {
            this.TBLBKMPLAN = new HashSet<TBLBKMPLAN>();
            this.TBLBKMSOZDET = new HashSet<TBLBKMSOZDET>();
        }
    
        public int INCKEYNO { get; set; }
        public short SUBE_KODU { get; set; }
        public int MAKINCKEYNO { get; set; }
        public int BKMSBINCKEYNO { get; set; }
        public Nullable<int> SOZINCKEYNO { get; set; }
        public string BKMSURETIPI { get; set; }
        public decimal BKMSURESI { get; set; }
        public string SIKLIKSURETIPI { get; set; }
        public decimal SIKLIKSURESI { get; set; }
        public System.DateTime BKMBASTAR { get; set; }
        public string AKTIF { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<decimal> FYEDEK1 { get; set; }
        public Nullable<decimal> FYEDEK2 { get; set; }
        public Nullable<System.DateTime> DYEDEK1 { get; set; }
        public Nullable<System.DateTime> DYEDEK2 { get; set; }
        public string STRYEDEK1 { get; set; }
        public string STRYEDEK2 { get; set; }
        public string SIKLIKTIPI { get; set; }
        public string DURUMTIPI1 { get; set; }
        public string DURUMTIPI2 { get; set; }
        public Nullable<decimal> DURUMDEGER1 { get; set; }
        public Nullable<decimal> DURUMDEGER2 { get; set; }
        public string DURUMSURETIPI1 { get; set; }
        public string DURUMSURETIPI2 { get; set; }
        public string DURUMOPERATOR { get; set; }
        public int MAKTIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMPLAN> TBLBKMPLAN { get; set; }
        public virtual TBLBKMSB TBLBKMSB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMSOZDET> TBLBKMSOZDET { get; set; }
        public virtual TBLBKMSOZMAS TBLBKMSOZMAS { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
