//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNPMRELDET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLNPMRELDET()
        {
            this.TBLNPMNODEINFO = new HashSet<TBLNPMNODEINFO>();
        }
    
        public int RELMASINCKEYNO { get; set; }
        public Nullable<int> CONNECTORKEYNO { get; set; }
        public int INCKEYNO { get; set; }
        public int EXECLIST { get; set; }
        public int ORDERNO { get; set; }
        public short OBJ_TYPE { get; set; }
        public string CAPTION { get; set; }
        public string REPEATED { get; set; }
        public Nullable<int> COLOR { get; set; }
        public Nullable<int> MODNO { get; set; }
        public Nullable<int> PROGNO { get; set; }
        public string CONDITION { get; set; }
        public string INFO { get; set; }
        public string READAFTEXEC { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<int> IYEDEK3 { get; set; }
        public Nullable<int> IYEDEK4 { get; set; }
        public Nullable<decimal> FYEDEK1 { get; set; }
        public Nullable<decimal> FYEDEK2 { get; set; }
        public Nullable<decimal> FYEDEK3 { get; set; }
        public Nullable<decimal> FYEDEK4 { get; set; }
        public Nullable<System.DateTime> DYEDEK1 { get; set; }
        public Nullable<System.DateTime> DYEDEK2 { get; set; }
        public Nullable<System.DateTime> DYEDEK3 { get; set; }
        public Nullable<System.DateTime> DYEDEK4 { get; set; }
        public string SYEDEK1 { get; set; }
        public string SYEDEK2 { get; set; }
        public string SYEDEK3 { get; set; }
        public string SYEDEK4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNPMNODEINFO> TBLNPMNODEINFO { get; set; }
        public virtual TBLNPMRELMAS TBLNPMRELMAS { get; set; }
    }
}
