//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNPMLOG
    {
        public int INCKEYNO { get; set; }
        public short SUBE_KODU { get; set; }
        public short KULLANICI_NO { get; set; }
        public int NPMRELMASINCKEYNO { get; set; }
        public int NPMRELDETINCKEYNO { get; set; }
        public int NPMMAINEXECKEYNO { get; set; }
        public int EXECGROUPID { get; set; }
        public string MSG { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> MSGDT { get; set; }
        public Nullable<System.DateTime> MSGENDDT { get; set; }
        public Nullable<byte> MSGTYPE { get; set; }
        public Nullable<short> MODNO { get; set; }
        public Nullable<short> PROGNO { get; set; }
        public Nullable<byte> ACTION { get; set; }
        public string RTM { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public string CYEDEK3 { get; set; }
        public string CYEDEK4 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<decimal> FYEDEK1 { get; set; }
        public Nullable<decimal> FYEDEK2 { get; set; }
        public Nullable<System.DateTime> DYEDEK1 { get; set; }
        public Nullable<System.DateTime> DYEDEK2 { get; set; }
        public string SYEDEK1 { get; set; }
        public string SYEDEK2 { get; set; }
    
        public virtual TBLKULLANP TBLKULLANP { get; set; }
        public virtual TBLNPMRELMAS TBLNPMRELMAS { get; set; }
    }
}
