//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOPERATIONS_KATALOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOPERATIONS_KATALOG()
        {
            this.TBLIUPCZG = new HashSet<TBLIUPCZG>();
            this.TBLKAPASITE = new HashSet<TBLKAPASITE>();
            this.TBLKKCARISTOK = new HashSet<TBLKKCARISTOK>();
            this.TBLOPGECISSURE = new HashSet<TBLOPGECISSURE>();
            this.TBLOPGECISSURE1 = new HashSet<TBLOPGECISSURE>();
            this.TBLROTATRA = new HashSet<TBLROTATRA>();
        }
    
        public short ISLETME_KODU { get; set; }
        public string OPKODU { get; set; }
        public string OPISIM { get; set; }
        public string ISTKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> OPMIK { get; set; }
        public Nullable<decimal> OVERLAPMIK { get; set; }
        public Nullable<decimal> SETUPSURE { get; set; }
        public Nullable<decimal> PRODSURE { get; set; }
        public Nullable<decimal> GECISSURE { get; set; }
        public string GRUP { get; set; }
        public string URETSURETIPI { get; set; }
        public Nullable<decimal> URETMIKTARI { get; set; }
        public string URETMIKTARITIPI { get; set; }
        public string SETUPSURETIPI { get; set; }
        public Nullable<decimal> PARTIMIKTARI { get; set; }
        public string PARTIMIKTARITIPI { get; set; }
        public string GECISSURETIPI { get; set; }
        public string GECISMIKTIPI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string GECISMIK_TANIMTIPI { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLISTASYON TBLISTASYON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIUPCZG> TBLIUPCZG { get; set; }
        public virtual TBLOPERASYONEK TBLOPERASYONEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKAPASITE> TBLKAPASITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKKCARISTOK> TBLKKCARISTOK { get; set; }
        public virtual TBLURETOPGRUP TBLURETOPGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOPGECISSURE> TBLOPGECISSURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOPGECISSURE> TBLOPGECISSURE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLROTATRA> TBLROTATRA { get; set; }
    }
}
