//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOTEL
    {
        public short ISLETME_KODU { get; set; }
        public string SUBE_KODU { get; set; }
        public Nullable<System.DateTime> BASTAR { get; set; }
        public Nullable<System.DateTime> BITTAR { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<int> UCR_MIS { get; set; }
        public Nullable<int> TUM_MIS { get; set; }
        public string STOK_KODU { get; set; }
        public Nullable<decimal> AMBDEVMIK { get; set; }
        public Nullable<decimal> AMBDEVFIY { get; set; }
        public Nullable<decimal> AMBALMIK { get; set; }
        public Nullable<decimal> AMBALFIY { get; set; }
        public Nullable<decimal> AMBCIKMIK { get; set; }
        public Nullable<decimal> AMBCIKFIY { get; set; }
        public Nullable<decimal> SUBEDEVMIK { get; set; }
        public Nullable<decimal> SUBEDEVFIY { get; set; }
        public Nullable<decimal> SUBEGIRMIK { get; set; }
        public Nullable<decimal> SUBEGIRFIY { get; set; }
        public Nullable<decimal> SUBEELMIK { get; set; }
        public Nullable<decimal> SUBEELFIY { get; set; }
        public Nullable<decimal> SUBEKULMIK { get; set; }
        public Nullable<decimal> SUBEKULFIY { get; set; }
    }
}
