//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOZELHESAP
    {
        public int BORCNO { get; set; }
        public int ALACAKNO { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public Nullable<int> L_YEDEK1 { get; set; }
        public Nullable<int> L_YEDEK2 { get; set; }
        public Nullable<decimal> TUTAR_ALACAK { get; set; }
        public Nullable<decimal> KURBORC { get; set; }
        public Nullable<decimal> KURALACAK { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
    }
}
