//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPOSODEME
    {
        public byte POS_TIPI { get; set; }
        public short SUBE_KODU { get; set; }
        public string ODEME_TIP { get; set; }
        public string ODEME_CRKS { get; set; }
        public string ODEME_KOD { get; set; }
        public string SYEDEK { get; set; }
        public string CYEDEK { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        public virtual TBLPOSPARAM TBLPOSPARAM { get; set; }
    }
}
