//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPLANLAMA_RAPORU_DETAY
    {
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string STOK_KODU { get; set; }
        public string SIPNO { get; set; }
        public string CARI_KODU { get; set; }
        public Nullable<System.DateTime> SIPTAR { get; set; }
        public Nullable<System.DateTime> TESTAR { get; set; }
        public Nullable<decimal> MUSTERI_SIP_BAK { get; set; }
        public Nullable<decimal> TESLIM_ET { get; set; }
        public Nullable<decimal> SONRA_BAK { get; set; }
        public Nullable<decimal> SONRA_TESLIM_ET { get; set; }
        public Nullable<decimal> KALAN_MUSSIP_BAK { get; set; }
        public Nullable<decimal> KALAN_STOK_BAK { get; set; }
        public Nullable<decimal> URET_SATIN_AL { get; set; }
        public Nullable<int> INCKEYNO { get; set; }
        public Nullable<decimal> MUS_SIP_MIK { get; set; }
        public Nullable<decimal> MUS_TES_MIK { get; set; }
        public Nullable<decimal> SEVK_MIK { get; set; }
        public Nullable<decimal> YUKLE_MIK { get; set; }
        public string YAPKOD { get; set; }
    
        public virtual TBLCASABIT TBLCASABIT { get; set; }
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
