//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPROJE()
        {
            this.TBLAFATUPRM = new HashSet<TBLAFATUPRM>();
            this.TBLBAGLANTI = new HashSet<TBLBAGLANTI>();
            this.TBLBCEK = new HashSet<TBLBCEK>();
            this.TBLBCEKPARCA = new HashSet<TBLBCEKPARCA>();
            this.TBLBNKHESKSTDETAY = new HashSet<TBLBNKHESKSTDETAY>();
            this.TBLBNKHESTRA = new HashSet<TBLBNKHESTRA>();
            this.TBLBNKLOGTRA = new HashSet<TBLBNKLOGTRA>();
            this.TBLBNKMSRF = new HashSet<TBLBNKMSRF>();
            this.TBLBNKTEMSABIT = new HashSet<TBLBNKTEMSABIT>();
            this.TBLBNKTEMTRA = new HashSet<TBLBNKTEMTRA>();
            this.TBLBNKTEMTRA1 = new HashSet<TBLBNKTEMTRA>();
            this.TBLBNKTEMTRA2 = new HashSet<TBLBNKTEMTRA>();
            this.TBLBORDROMAS = new HashSet<TBLBORDROMAS>();
            this.TBLBSEN = new HashSet<TBLBSEN>();
            this.TBLBSENPARCA = new HashSet<TBLBSENPARCA>();
            this.TBLCAHAR = new HashSet<TBLCAHAR>();
            this.TBLCARIPLASIYER = new HashSet<TBLCARIPLASIYER>();
            this.TBLCARISTOK = new HashSet<TBLCARISTOK>();
            this.TBLCRMANKSABIT = new HashSet<TBLCRMANKSABIT>();
            this.TBLCRMSKYSABIT = new HashSet<TBLCRMSKYSABIT>();
            this.TBLDAMGAVERGISI = new HashSet<TBLDAMGAVERGISI>();
            this.TBLDEKOTRA = new HashSet<TBLDEKOTRA>();
            this.TBLFATUIRS = new HashSet<TBLFATUIRS>();
            this.TBLHESTEMP = new HashSet<TBLHESTEMP>();
            this.TBLISEMRI = new HashSet<TBLISEMRI>();
            this.TBLISEMRIREC = new HashSet<TBLISEMRIREC>();
            this.TBLKARTODEMETRA = new HashSet<TBLKARTODEMETRA>();
            this.TBLKASA = new HashSet<TBLKASA>();
            this.TBLKKMAS = new HashSet<TBLKKMAS>();
            this.TBLKRTODEME = new HashSet<TBLKRTODEME>();
            this.TBLKRTTHSLT = new HashSet<TBLKRTTHSLT>();
            this.TBLMALIGRUP = new HashSet<TBLMALIGRUP>();
            this.TBLMASRAFTRA = new HashSet<TBLMASRAFTRA>();
            this.TBLMCEK = new HashSet<TBLMCEK>();
            this.TBLMCEKPARCA = new HashSet<TBLMCEKPARCA>();
            this.TBLMSEN = new HashSet<TBLMSEN>();
            this.TBLMSENPARCA = new HashSet<TBLMSENPARCA>();
            this.TBLMUHAGEC = new HashSet<TBLMUHAGEC>();
            this.TBLMUHFIS = new HashSet<TBLMUHFIS>();
            this.TBLMUSTAHSI = new HashSet<TBLMUSTAHSI>();
            this.TBLMUSTOZELKESPROJE = new HashSet<TBLMUSTOZELKESPROJE>();
            this.TBLODEEMIR = new HashSet<TBLODEEMIR>();
            this.TBLPROFORMAMAS = new HashSet<TBLPROFORMAMAS>();
            this.TBLPROFORMATRA = new HashSet<TBLPROFORMATRA>();
            this.TEMP_MUHAGEC = new HashSet<TEMP_MUHAGEC>();
            this.TBLPROJESIRKET = new HashSet<TBLPROJESIRKET>();
            this.TBLREPLANISH = new HashSet<TBLREPLANISH>();
            this.TBLSAYIM = new HashSet<TBLSAYIM>();
            this.TBLSFATUPRM = new HashSet<TBLSFATUPRM>();
            this.TBLSIPAMAS = new HashSet<TBLSIPAMAS>();
            this.TBLSIPATRA = new HashSet<TBLSIPATRA>();
            this.TBLSTHAR = new HashSet<TBLSTHAR>();
            this.TBLSTOKURS = new HashSet<TBLSTOKURS>();
            this.TBLTEKLIFMAS = new HashSet<TBLTEKLIFMAS>();
            this.TBLTEKLIFPRM = new HashSet<TBLTEKLIFPRM>();
            this.TBLTEKLIFTRA = new HashSet<TBLTEKLIFTRA>();
            this.TBLTEMPHAIS = new HashSet<TBLTEMPHAIS>();
            this.TBLTMPDAGIT = new HashSet<TBLTMPDAGIT>();
            this.TBLTMPDISSIPATRA = new HashSet<TBLTMPDISSIPATRA>();
            this.TBLUAKMAS = new HashSet<TBLUAKMAS>();
        }
    
        public short ISLETME_KODU { get; set; }
        public string PROJE_KODU { get; set; }
        public string TUR { get; set; }
        public string PROJE_ACIKLAMA { get; set; }
        public string RAPOR_KOD1 { get; set; }
        public string RAPOR_KOD2 { get; set; }
        public string REF_KOD { get; set; }
        public string SORUMLU { get; set; }
        public string DURUM { get; set; }
        public Nullable<short> AKTIF { get; set; }
        public Nullable<System.DateTime> BASTAR { get; set; }
        public Nullable<System.DateTime> BITTAR { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<decimal> FYEDEK1 { get; set; }
        public Nullable<decimal> FYEDEK2 { get; set; }
        public Nullable<System.DateTime> DYEDEK1 { get; set; }
        public Nullable<System.DateTime> DYEDEK2 { get; set; }
        public string STRYEDEK1 { get; set; }
        public string STRYEDEK2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAFATUPRM> TBLAFATUPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBAGLANTI> TBLBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCEK> TBLBCEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCEKPARCA> TBLBCEKPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKHESKSTDETAY> TBLBNKHESKSTDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKHESTRA> TBLBNKHESTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKLOGTRA> TBLBNKLOGTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKMSRF> TBLBNKMSRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKTEMSABIT> TBLBNKTEMSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKTEMTRA> TBLBNKTEMTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKTEMTRA> TBLBNKTEMTRA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKTEMTRA> TBLBNKTEMTRA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBORDROMAS> TBLBORDROMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBSEN> TBLBSEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBSENPARCA> TBLBSENPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCAHAR> TBLCAHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIPLASIYER> TBLCARIPLASIYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARISTOK> TBLCARISTOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKSABIT> TBLCRMANKSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYSABIT> TBLCRMSKYSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAMGAVERGISI> TBLDAMGAVERGISI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEKOTRA> TBLDEKOTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUIRS> TBLFATUIRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHESTEMP> TBLHESTEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISEMRI> TBLISEMRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISEMRIREC> TBLISEMRIREC { get; set; }
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKARTODEMETRA> TBLKARTODEMETRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASA> TBLKASA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKKMAS> TBLKKMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTODEME> TBLKRTODEME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTTHSLT> TBLKRTTHSLT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALIGRUP> TBLMALIGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMASRAFTRA> TBLMASRAFTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMCEK> TBLMCEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMCEKPARCA> TBLMCEKPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMSEN> TBLMSEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMSENPARCA> TBLMSENPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHAGEC> TBLMUHAGEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHFIS> TBLMUHFIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTAHSI> TBLMUSTAHSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTOZELKESPROJE> TBLMUSTOZELKESPROJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLODEEMIR> TBLODEEMIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPROFORMAMAS> TBLPROFORMAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPROFORMATRA> TBLPROFORMATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_MUHAGEC> TEMP_MUHAGEC { get; set; }
        public virtual TBLPROJEEK TBLPROJEEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPROJESIRKET> TBLPROJESIRKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREPLANISH> TBLREPLANISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAYIM> TBLSAYIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSFATUPRM> TBLSFATUPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPAMAS> TBLSIPAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPATRA> TBLSIPATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTHAR> TBLSTHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKURS> TBLSTOKURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFMAS> TBLTEKLIFMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFPRM> TBLTEKLIFPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFTRA> TBLTEKLIFTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEMPHAIS> TBLTEMPHAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDAGIT> TBLTMPDAGIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDISSIPATRA> TBLTMPDISSIPATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUAKMAS> TBLUAKMAS { get; set; }
    }
}
