//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRJDETAYSABLON
    {
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string RAPORKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<short> COKLUYIL { get; set; }
        public Nullable<short> KUMULE { get; set; }
        public string PROJEKISIT { get; set; }
        public string RAPORKISIT { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<double> FYEDEK1 { get; set; }
        public Nullable<double> FYEDEK2 { get; set; }
        public Nullable<System.DateTime> DYEDEK1 { get; set; }
        public Nullable<System.DateTime> DYEDEK2 { get; set; }
        public string SYEDEK1 { get; set; }
        public string SYEDEK2 { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
