//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTOKFIATKOD
    {
        public short ISLETME_KODU { get; set; }
        public string FIYATKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string SORUMLUGRUP { get; set; }
        public Nullable<decimal> KARMARJI { get; set; }
        public string ALT_UST { get; set; }
        public string SATISFIATKDVDAHIL { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
    }
}
