//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIPMALMUS
    {
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string STOK_KODU { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<decimal> BAGSIPMIK { get; set; }
        public Nullable<decimal> STAYSIPMIK { get; set; }
        public Nullable<decimal> TOPSIPMIK { get; set; }
        public Nullable<decimal> TOPSIPTUT { get; set; }
        public Nullable<decimal> BAGTESMIK { get; set; }
        public Nullable<decimal> STAYTESMIK { get; set; }
        public Nullable<decimal> TOPTESMIK { get; set; }
        public Nullable<decimal> TOPTESTUT { get; set; }
        public Nullable<decimal> BAGFARKMIK { get; set; }
        public Nullable<decimal> STAYFARKMIK { get; set; }
        public Nullable<decimal> FARKMIK { get; set; }
        public Nullable<decimal> FARKTUT { get; set; }
        public Nullable<decimal> STOK_MIK { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK5 { get; set; }
        public Nullable<decimal> F_YEDEK6 { get; set; }
        public string YAPKOD { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
