//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTOKKOLI
    {
        public string KOLISTOK_KODU { get; set; }
        public string KOLIYAPKOD { get; set; }
        public string BILESENSTOK_KODU { get; set; }
        public string BILESENYAPKOD { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public string BILGIAMACLI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string PROJE_KODU { get; set; }
        public string BILESENOZELFIYAT { get; set; }
        public string BILESENISKONTO { get; set; }
        public int INCKEYNO { get; set; }
        public Nullable<decimal> MALFAZLASI { get; set; }
        public string KOLIKDV { get; set; }
        public Nullable<decimal> ISKORAN { get; set; }
    
        public virtual TBLESNYAPMAS TBLESNYAPMAS { get; set; }
        public virtual TBLESNYAPMAS TBLESNYAPMAS1 { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT1 { get; set; }
    }
}
