//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSABLONTRA
    {
        public int INCKEYNO { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELDNAME { get; set; }
        public string FIELDTYPE { get; set; }
        public Nullable<short> LROW { get; set; }
        public Nullable<short> COL { get; set; }
        public Nullable<short> LEN { get; set; }
        public string TRIM { get; set; }
        public string DECIMALSEP { get; set; }
        public string THOUSANDSEP { get; set; }
        public string DEFVALUE { get; set; }
        public Nullable<short> DECCOUNT { get; set; }
        public string SCRIPT { get; set; }
    
        public virtual TBLSABLONMAS TBLSABLONMAS { get; set; }
    }
}
