//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSUBELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSUBELER()
        {
            this.TBLBAGLANTI = new HashSet<TBLBAGLANTI>();
            this.TBLBCEK = new HashSet<TBLBCEK>();
            this.TBLBCEKPARCA = new HashSet<TBLBCEKPARCA>();
            this.TBLBFORMMAS = new HashSet<TBLBFORMMAS>();
            this.TBLBFORMMASEK = new HashSet<TBLBFORMMASEK>();
            this.TBLBKMDURUM = new HashSet<TBLBKMDURUM>();
            this.TBLBKMPLAN = new HashSet<TBLBKMPLAN>();
            this.TBLBKMSB = new HashSet<TBLBKMSB>();
            this.TBLBKMSOZMAS = new HashSet<TBLBKMSOZMAS>();
            this.TBLBKMSOZTIP = new HashSet<TBLBKMSOZTIP>();
            this.TBLBKMTALEP = new HashSet<TBLBKMTALEP>();
            this.TBLBKMTALEPKONTROL = new HashSet<TBLBKMTALEPKONTROL>();
            this.TBLBKMTIP = new HashSet<TBLBKMTIP>();
            this.TBLBKMTRA = new HashSet<TBLBKMTRA>();
            this.TBLBNKDESENMAS = new HashSet<TBLBNKDESENMAS>();
            this.TBLBNKHESKSTDETAY = new HashSet<TBLBNKHESKSTDETAY>();
            this.TBLBNKHESSABIT = new HashSet<TBLBNKHESSABIT>();
            this.TBLBNKHESTRA = new HashSet<TBLBNKHESTRA>();
            this.TBLBNKKURUMMAS = new HashSet<TBLBNKKURUMMAS>();
            this.TBLBNKLOGTRA = new HashSet<TBLBNKLOGTRA>();
            this.TBLBNKMUHVIRMAN = new HashSet<TBLBNKMUHVIRMAN>();
            this.TBLBNKODEPLAN = new HashSet<TBLBNKODEPLAN>();
            this.TBLBNKONLOTMODEME = new HashSet<TBLBNKONLOTMODEME>();
            this.TBLBNKONLOTMTRANS = new HashSet<TBLBNKONLOTMTRANS>();
            this.TBLBNKSCENTEGREMAS = new HashSet<TBLBNKSCENTEGREMAS>();
            this.TBLBNKSCENTEGRETRA = new HashSet<TBLBNKSCENTEGRETRA>();
            this.TBLBNKTEMSABIT = new HashSet<TBLBNKTEMSABIT>();
            this.TBLBSCMODELMAS = new HashSet<TBLBSCMODELMAS>();
            this.TBLBSEN = new HashSet<TBLBSEN>();
            this.TBLBSENPARCA = new HashSet<TBLBSENPARCA>();
            this.TBLBUTCEBILESENROLTRA = new HashSet<TBLBUTCEBILESENROLTRA>();
            this.TBLBUTCEMAS = new HashSet<TBLBUTCEMAS>();
            this.TBLBUTCEODEPLANMAS = new HashSet<TBLBUTCEODEPLANMAS>();
            this.TBLBUTCEROLTRA = new HashSet<TBLBUTCEROLTRA>();
            this.TBLCAGRUP = new HashSet<TBLCAGRUP>();
            this.TBLCAHAR = new HashSet<TBLCAHAR>();
            this.TBLCARIKOD1 = new HashSet<TBLCARIKOD1>();
            this.TBLCARIKOD2 = new HashSet<TBLCARIKOD2>();
            this.TBLCARIKOD3 = new HashSet<TBLCARIKOD3>();
            this.TBLCARIKOD4 = new HashSet<TBLCARIKOD4>();
            this.TBLCARIKOD5 = new HashSet<TBLCARIKOD5>();
            this.TBLCARIKUR = new HashSet<TBLCARIKUR>();
            this.TBLCARIPLASIYER = new HashSet<TBLCARIPLASIYER>();
            this.TBLCARISTOK = new HashSet<TBLCARISTOK>();
            this.TBLCASABIT = new HashSet<TBLCASABIT>();
            this.TBLCEKSENDEK = new HashSet<TBLCEKSENDEK>();
            this.TBLCEKSENETTAHESLES = new HashSet<TBLCEKSENETTAHESLES>();
            this.TBLCIZELGETASLAK = new HashSet<TBLCIZELGETASLAK>();
            this.TBLCONFIGACIKLAMALAR = new HashSet<TBLCONFIGACIKLAMALAR>();
            this.TBLCONFIGALTERNATIFGRUP = new HashSet<TBLCONFIGALTERNATIFGRUP>();
            this.TBLCONFIGBAGLANTI = new HashSet<TBLCONFIGBAGLANTI>();
            this.TBLCONFIGBELGELER = new HashSet<TBLCONFIGBELGELER>();
            this.TBLCONFIGBIRLIKKALEMMAS = new HashSet<TBLCONFIGBIRLIKKALEMMAS>();
            this.TBLCONFIGBIRLIKKALEMTRA = new HashSet<TBLCONFIGBIRLIKKALEMTRA>();
            this.TBLCONFIGDEGER = new HashSet<TBLCONFIGDEGER>();
            this.TBLCONFIGKURALLAR = new HashSet<TBLCONFIGKURALLAR>();
            this.TBLCONFIGMAS = new HashSet<TBLCONFIGMAS>();
            this.TBLCONFIGOZELLIK = new HashSet<TBLCONFIGOZELLIK>();
            this.TBLCONFIGPARAMS = new HashSet<TBLCONFIGPARAMS>();
            this.TBLCONFIGTRA = new HashSet<TBLCONFIGTRA>();
            this.TBLCONFIGURUNGRUP = new HashSet<TBLCONFIGURUNGRUP>();
            this.TBLCONFIGURUNGRUPBAGLANTI = new HashSet<TBLCONFIGURUNGRUPBAGLANTI>();
            this.TBLCONFIGURUNGRUPMAMULBAGLANTI = new HashSet<TBLCONFIGURUNGRUPMAMULBAGLANTI>();
            this.TBLCONFIGYENIOZELLIKDEGERLER = new HashSet<TBLCONFIGYENIOZELLIKDEGERLER>();
            this.TBLCRMADAY = new HashSet<TBLCRMADAY>();
            this.TBLCRMANKGRUP = new HashSet<TBLCRMANKGRUP>();
            this.TBLCRMANKICERIK = new HashSet<TBLCRMANKICERIK>();
            this.TBLCRMANKICERIKGRUP = new HashSet<TBLCRMANKICERIKGRUP>();
            this.TBLCRMANKSABIT = new HashSet<TBLCRMANKSABIT>();
            this.TBLCRMEXCHANGELOG = new HashSet<TBLCRMEXCHANGELOG>();
            this.TBLCRMEXCHANGEMAS = new HashSet<TBLCRMEXCHANGEMAS>();
            this.TBLCRMEXCHANGEPRM = new HashSet<TBLCRMEXCHANGEPRM>();
            this.TBLCRMEXCHANGETRA = new HashSet<TBLCRMEXCHANGETRA>();
            this.TBLCRMFIRSAT = new HashSet<TBLCRMFIRSAT>();
            this.TBLCRMKAYIPNEDEN = new HashSet<TBLCRMKAYIPNEDEN>();
            this.TBLCRMKULLANP = new HashSet<TBLCRMKULLANP>();
            this.TBLCRMPAZAKT = new HashSet<TBLCRMPAZAKT>();
            this.TBLCRMPAZAKT1 = new HashSet<TBLCRMPAZAKT>();
            this.TBLCRMPAZALTAKT = new HashSet<TBLCRMPAZALTAKT>();
            this.TBLCRMSABLON = new HashSet<TBLCRMSABLON>();
            this.TBLCRMSATAKT = new HashSet<TBLCRMSATAKT>();
            this.TBLCRMSATASAMASI = new HashSet<TBLCRMSATASAMASI>();
            this.TBLCRMSKYAKT = new HashSet<TBLCRMSKYAKT>();
            this.TBLCRMSKYAKTTIP = new HashSet<TBLCRMSKYAKTTIP>();
            this.TBLCRMSKYDURUM = new HashSet<TBLCRMSKYDURUM>();
            this.TBLCRMSKYGRUP = new HashSet<TBLCRMSKYGRUP>();
            this.TBLCRMSKYSABIT = new HashSet<TBLCRMSKYSABIT>();
            this.TBLCRMWIZARDDATA = new HashSet<TBLCRMWIZARDDATA>();
            this.TBLDAGAKTARIMLOG = new HashSet<TBLDAGAKTARIMLOG>();
            this.TBLDAGDISPATCH = new HashSet<TBLDAGDISPATCH>();
            this.TBLDAGFUNCHIST = new HashSet<TBLDAGFUNCHIST>();
            this.TBLDAGROTAGRUPLARI = new HashSet<TBLDAGROTAGRUPLARI>();
            this.TBLDAGROTASABIT = new HashSet<TBLDAGROTASABIT>();
            this.TBLDAGVASITABILGI = new HashSet<TBLDAGVASITABILGI>();
            this.TBLDAMGAVERGISI = new HashSet<TBLDAMGAVERGISI>();
            this.TBLDBSFATURAMAS = new HashSet<TBLDBSFATURAMAS>();
            this.TBLDBSFATURATRA = new HashSet<TBLDBSFATURATRA>();
            this.TBLDBSLIMITRISK = new HashSet<TBLDBSLIMITRISK>();
            this.TBLDEKOMAS = new HashSet<TBLDEKOMAS>();
            this.TBLDEKONO = new HashSet<TBLDEKONO>();
            this.TBLDEKOTRA = new HashSet<TBLDEKOTRA>();
            this.TBLDEKOTRAEK = new HashSet<TBLDEKOTRAEK>();
            this.TBLDEPMAS = new HashSet<TBLDEPMAS>();
            this.TBLDEPOKILIT = new HashSet<TBLDEPOKILIT>();
            this.TBLDEPSAYIM = new HashSet<TBLDEPSAYIM>();
            this.TBLDEPSAYIMSERI = new HashSet<TBLDEPSAYIMSERI>();
            this.TBLDEPTESAYRIBAKIYE = new HashSet<TBLDEPTESAYRIBAKIYE>();
            this.TBLDIZAYNMOD = new HashSet<TBLDIZAYNMOD>();
            this.TBLDIZAYNSABIT = new HashSet<TBLDIZAYNSABIT>();
            this.TBLDZNBASIMLOG = new HashSet<TBLDZNBASIMLOG>();
            this.TBLEARSIV = new HashSet<TBLEARSIV>();
            this.TBLEATIK = new HashSet<TBLEATIK>();
            this.TBLEFATPRM = new HashSet<TBLEFATPRM>();
            this.TBLEFATURA = new HashSet<TBLEFATURA>();
            this.TBLEFATZARF = new HashSet<TBLEFATZARF>();
            this.TBLEMUSTAHSIL = new HashSet<TBLEMUSTAHSIL>();
            this.TBLEMUTABAKATLOG = new HashSet<TBLEMUTABAKATLOG>();
            this.TBLEMUTABAKATMAS = new HashSet<TBLEMUTABAKATMAS>();
            this.TBLEMUTABAKATSUBETANIM = new HashSet<TBLEMUTABAKATSUBETANIM>();
            this.TBLENETOZELDURUM = new HashSet<TBLENETOZELDURUM>();
            this.TBLENETPORTLETMAS = new HashSet<TBLENETPORTLETMAS>();
            this.TBLENETSEPET = new HashSet<TBLENETSEPET>();
            this.TBLENETSIPSABLON = new HashSet<TBLENETSIPSABLON>();
            this.TBLEPOSTALOG = new HashSet<TBLEPOSTALOG>();
            this.TBLESNYAPNUM = new HashSet<TBLESNYAPNUM>();
            this.TBLFAILUREPREQUISITION = new HashSet<TBLFAILUREPREQUISITION>();
            this.TBLFATUEK = new HashSet<TBLFATUEK>();
            this.TBLFATUIRS = new HashSet<TBLFATUIRS>();
            this.TBLFATUIRSEK = new HashSet<TBLFATUIRSEK>();
            this.TBLFATUSERI = new HashSet<TBLFATUSERI>();
            this.TBLFATUVADE = new HashSet<TBLFATUVADE>();
            this.TBLFIATGRUP = new HashSet<TBLFIATGRUP>();
            this.TBLFINANSTEMP = new HashSet<TBLFINANSTEMP>();
            this.TBLFIYATLISTINFO = new HashSet<TBLFIYATLISTINFO>();
            this.TBLFIYFARKMAS = new HashSet<TBLFIYFARKMAS>();
            this.TBLHALMASRAFEK = new HashSet<TBLHALMASRAFEK>();
            this.TBLHASHTAGTRA = new HashSet<TBLHASHTAGTRA>();
            this.TBLHESKODESLES = new HashSet<TBLHESKODESLES>();
            this.TBLIMZALOG = new HashSet<TBLIMZALOG>();
            this.TBLINDKDVLOG = new HashSet<TBLINDKDVLOG>();
            this.TBLKAMYONSB = new HashSet<TBLKAMYONSB>();
            this.TBLKANTPRM = new HashSet<TBLKANTPRM>();
            this.TBLKARGOISLEM = new HashSet<TBLKARGOISLEM>();
            this.TBLKARGOKULLANICI = new HashSet<TBLKARGOKULLANICI>();
            this.TBLKARTODEMETRA = new HashSet<TBLKARTODEMETRA>();
            this.TBLKASA = new HashSet<TBLKASA>();
            this.TBLKASAEK = new HashSet<TBLKASAEK>();
            this.TBLKASAMAS = new HashSet<TBLKASAMAS>();
            this.TBLKEFILTRA = new HashSet<TBLKEFILTRA>();
            this.TBLKODEKRANBAGLANTI = new HashSet<TBLKODEKRANBAGLANTI>();
            this.TBLKODHARICHAR = new HashSet<TBLKODHARICHAR>();
            this.TBLKOSTIPMAS = new HashSet<TBLKOSTIPMAS>();
            this.TBLKOSULMAS = new HashSet<TBLKOSULMAS>();
            this.TBLKOSVADEMAS = new HashSet<TBLKOSVADEMAS>();
            this.TBLKRTODEME = new HashSet<TBLKRTODEME>();
            this.TBLKRTSOZMAS = new HashSet<TBLKRTSOZMAS>();
            this.TBLKRTTHSLT = new HashSet<TBLKRTTHSLT>();
            this.TBLKRTTHSLTEK = new HashSet<TBLKRTTHSLTEK>();
            this.TBLKULEMAIL = new HashSet<TBLKULEMAIL>();
            this.TBLKULHAKDEVIR = new HashSet<TBLKULHAKDEVIR>();
            this.TBLKULLANHAKP = new HashSet<TBLKULLANHAKP>();
            this.TBLKULLANHAKTALEP = new HashSet<TBLKULLANHAKTALEP>();
            this.TBLKULLANP = new HashSet<TBLKULLANP>();
            this.TBLKULLANPROGP = new HashSet<TBLKULLANPROGP>();
            this.TBLKVKK = new HashSet<TBLKVKK>();
            this.TBLLOCKEDDATAMAS = new HashSet<TBLLOCKEDDATAMAS>();
            this.TBLLOGKULTABLOLAR = new HashSet<TBLLOGKULTABLOLAR>();
            this.TBLMAKBKM = new HashSet<TBLMAKBKM>();
            this.TBLMAKBKMMASRAFFAT = new HashSet<TBLMAKBKMMASRAFFAT>();
            this.TBLMAKKATSAYI = new HashSet<TBLMAKKATSAYI>();
            this.TBLMAKMALIYET = new HashSet<TBLMAKMALIYET>();
            this.TBLMAKMSRMAS = new HashSet<TBLMAKMSRMAS>();
            this.TBLMAKSARF = new HashSet<TBLMAKSARF>();
            this.TBLMALISIRA = new HashSet<TBLMALISIRA>();
            this.TBLMASRAF = new HashSet<TBLMASRAF>();
            this.TBLMASRAFMAS = new HashSet<TBLMASRAFMAS>();
            this.TBLMCEK = new HashSet<TBLMCEK>();
            this.TBLMCEKPARCA = new HashSet<TBLMCEKPARCA>();
            this.TBLMPSONCELIK = new HashSet<TBLMPSONCELIK>();
            this.TBLMRPSIPBELGELOG = new HashSet<TBLMRPSIPBELGELOG>();
            this.TBLMSEN = new HashSet<TBLMSEN>();
            this.TBLMSENPARCA = new HashSet<TBLMSENPARCA>();
            this.TBLMUHAGEC = new HashSet<TBLMUHAGEC>();
            this.TBLMUHAREF = new HashSet<TBLMUHAREF>();
            this.TBLMUHFIS = new HashSet<TBLMUHFIS>();
            this.TBLMUHFISEK = new HashSet<TBLMUHFISEK>();
            this.TBLMUHMAS = new HashSet<TBLMUHMAS>();
            this.TBLMUPLAN = new HashSet<TBLMUPLAN>();
            this.TBLMUPLANSUBE = new HashSet<TBLMUPLANSUBE>();
            this.TBLMUSCIRO = new HashSet<TBLMUSCIRO>();
            this.TBLMUSTAHSI = new HashSet<TBLMUSTAHSI>();
            this.TBLMUSTAHSIEK = new HashSet<TBLMUSTAHSIEK>();
            this.TBLMUSTERIMAYARLAR = new HashSet<TBLMUSTERIMAYARLAR>();
            this.TBLMUSTOZELKESINTI = new HashSet<TBLMUSTOZELKESINTI>();
            this.TBLMUSTOZELKESPROJE = new HashSet<TBLMUSTOZELKESPROJE>();
            this.TBLMUSTPRMEK = new HashSet<TBLMUSTPRMEK>();
            this.TBLNAKITAKIS_GELIRGIDERTIP = new HashSet<TBLNAKITAKIS_GELIRGIDERTIP>();
            this.TBLNAKITAKISMAS = new HashSet<TBLNAKITAKISMAS>();
            this.TBLNAKLIYE = new HashSet<TBLNAKLIYE>();
            this.TBLNDIBAGLANTI = new HashSet<TBLNDIBAGLANTI>();
            this.TBLNDS = new HashSet<TBLNDS>();
            this.TBLNETSISLOG = new HashSet<TBLNETSISLOG>();
            this.TBLNFDMAS = new HashSet<TBLNFDMAS>();
            this.TBLNPMRELMAS = new HashSet<TBLNPMRELMAS>();
            this.TBLNRPSHARING = new HashSet<TBLNRPSHARING>();
            this.TBLNTFPOOL = new HashSet<TBLNTFPOOL>();
            this.TBLODEEMIR = new HashSet<TBLODEEMIR>();
            this.TBLONLINEBANKLOG = new HashSet<TBLONLINEBANKLOG>();
            this.TBLPOSAKTARILANLAR = new HashSet<TBLPOSAKTARILANLAR>();
            this.TBLPOSPARAM = new HashSet<TBLPOSPARAM>();
            this.TBLPRGPRM = new HashSet<TBLPRGPRM>();
            this.TBLPRJDETAYSABLON = new HashSet<TBLPRJDETAYSABLON>();
            this.TBLPRJKUMULEMAS = new HashSet<TBLPRJKUMULEMAS>();
            this.TBLPRJKUMULETRA = new HashSet<TBLPRJKUMULETRA>();
            this.TBLPROFORMAMAS = new HashSet<TBLPROFORMAMAS>();
            this.TBLPROFORMATRA = new HashSet<TBLPROFORMATRA>();
            this.TBLRAPORSONUC = new HashSet<TBLRAPORSONUC>();
            this.TBLRAPORTASLAK = new HashSet<TBLRAPORTASLAK>();
            this.TBLRCPCONSUSERTRA = new HashSet<TBLRCPCONSUSERTRA>();
            this.TBLRCPMAS = new HashSet<TBLRCPMAS>();
            this.TBLRECMALIYET = new HashSet<TBLRECMALIYET>();
            this.TBLREPLANISH = new HashSet<TBLREPLANISH>();
            this.TBLREPORTSHARING = new HashSet<TBLREPORTSHARING>();
            this.TBLREVNO = new HashSet<TBLREVNO>();
            this.TBLROTABAGLANTI = new HashSet<TBLROTABAGLANTI>();
            this.TBLROTAMAS = new HashSet<TBLROTAMAS>();
            this.TBLROTATRA = new HashSet<TBLROTATRA>();
            this.TBLSABLONMAS = new HashSet<TBLSABLONMAS>();
            this.TBLSAHAACIKLAMA = new HashSet<TBLSAHAACIKLAMA>();
            this.TBLSATCIRO = new HashSet<TBLSATCIRO>();
            this.TBLSATISTANUSK = new HashSet<TBLSATISTANUSK>();
            this.TBLSAYIM = new HashSet<TBLSAYIM>();
            this.TBLSAYIMSERI = new HashSet<TBLSAYIMSERI>();
            this.TBLSERINUM = new HashSet<TBLSERINUM>();
            this.TBLSERITRA = new HashSet<TBLSERITRA>();
            this.TBLSEVKMAS = new HashSet<TBLSEVKMAS>();
            this.TBLSEVKTRA = new HashSet<TBLSEVKTRA>();
            this.TBLSILINENKAYITLAR = new HashSet<TBLSILINENKAYITLAR>();
            this.TBLSIPAMAS = new HashSet<TBLSIPAMAS>();
            this.TBLSIPATRA = new HashSet<TBLSIPATRA>();
            this.TBLSMSLOG = new HashSet<TBLSMSLOG>();
            this.TBLSMSMAS = new HashSet<TBLSMSMAS>();
            this.TBLSMSPHONELIST = new HashSet<TBLSMSPHONELIST>();
            this.TBLSMSTRA = new HashSet<TBLSMSTRA>();
            this.TBLSSATIRAC = new HashSet<TBLSSATIRAC>();
            this.TBLSTGRUP = new HashSet<TBLSTGRUP>();
            this.TBLSTHAR = new HashSet<TBLSTHAR>();
            this.TBLSTOK_MADABC = new HashSet<TBLSTOK_MADABC>();
            this.TBLSTOKDP = new HashSet<TBLSTOKDP>();
            this.TBLSTOKKOD1 = new HashSet<TBLSTOKKOD1>();
            this.TBLSTOKKOD2 = new HashSet<TBLSTOKKOD2>();
            this.TBLSTOKKOD3 = new HashSet<TBLSTOKKOD3>();
            this.TBLSTOKKOD4 = new HashSet<TBLSTOKKOD4>();
            this.TBLSTOKKOD5 = new HashSet<TBLSTOKKOD5>();
            this.TBLSTOKURS = new HashSet<TBLSTOKURS>();
            this.TBLSTSABIT = new HashSet<TBLSTSABIT>();
            this.TBLACIKREC = new HashSet<TBLACIKREC>();
            this.TBLAL12 = new HashSet<TBLAL12>();
            this.TBLDAGYUKNO = new HashSet<TBLDAGYUKNO>();
            this.TBLEFATUNO = new HashSet<TBLEFATUNO>();
            this.TBLEIRSYANITNO = new HashSet<TBLEIRSYANITNO>();
            this.TBLESNYAPNUMSTOK = new HashSet<TBLESNYAPNUMSTOK>();
            this.TBLFATUNO = new HashSet<TBLFATUNO>();
            this.TBLGENPOSPARAM = new HashSet<TBLGENPOSPARAM>();
            this.TBLMAKBLGNO = new HashSet<TBLMAKBLGNO>();
            this.TBLMAL12 = new HashSet<TBLMAL12>();
            this.TBLMALCIRO = new HashSet<TBLMALCIRO>();
            this.TEMP_MUHAGEC = new HashSet<TEMP_MUHAGEC>();
            this.TBLMUSMAL = new HashSet<TBLMUSMAL>();
            this.TBLMZAMBAR = new HashSet<TBLMZAMBAR>();
            this.TBLOZELKOD2KDVHESAP = new HashSet<TBLOZELKOD2KDVHESAP>();
            this.TBLPLANLAMA_RAPORU_DETAY = new HashSet<TBLPLANLAMA_RAPORU_DETAY>();
            this.TBLPLANLAMA_RAPORU_ICMAL = new HashSet<TBLPLANLAMA_RAPORU_ICMAL>();
            this.TBLGENPOSODEME = new HashSet<TBLGENPOSODEME>();
            this.TBLTMPPRJKUMULE = new HashSet<TBLTMPPRJKUMULE>();
            this.TBLSAT12 = new HashSet<TBLSAT12>();
            this.TBLSATMAL = new HashSet<TBLSATMAL>();
            this.TBLSIPMALMUS = new HashSet<TBLSIPMALMUS>();
            this.TBLSTMUHDETAY = new HashSet<TBLSTMUHDETAY>();
            this.TBLSTOKPH = new HashSet<TBLSTOKPH>();
            this.TBLSUBISEMRI = new HashSet<TBLSUBISEMRI>();
            this.TBLURETSUBOPERATIONS = new HashSet<TBLURETSUBOPERATIONS>();
            this.TBLSWIFTDOCMAS = new HashSet<TBLSWIFTDOCMAS>();
            this.TBLTEKLIFMAS = new HashSet<TBLTEKLIFMAS>();
            this.TBLTEKLIFPRM = new HashSet<TBLTEKLIFPRM>();
            this.TBLTEKLIFTRA = new HashSet<TBLTEKLIFTRA>();
            this.TBLTERAZIPARAM = new HashSet<TBLTERAZIPARAM>();
            this.TBLTEVKIFATKDVKOD = new HashSet<TBLTEVKIFATKDVKOD>();
            this.TBLTIPDETAY = new HashSet<TBLTIPDETAY>();
            this.TBLTMPBNKSCENTEGREMAS = new HashSet<TBLTMPBNKSCENTEGREMAS>();
            this.TBLTMPBNKSCENTEGRETRA = new HashSet<TBLTMPBNKSCENTEGRETRA>();
            this.TBLTMPDBSFATURAMAS = new HashSet<TBLTMPDBSFATURAMAS>();
            this.TBLTMPDBSFATURATRA = new HashSet<TBLTMPDBSFATURATRA>();
            this.TBLTMPDBSLIMITRISK = new HashSet<TBLTMPDBSLIMITRISK>();
            this.TBLTMPDISSIPATRA = new HashSet<TBLTMPDISSIPATRA>();
            this.TBLTMPEMIR = new HashSet<TBLTMPEMIR>();
            this.TBLUAKKAYNAK = new HashSet<TBLUAKKAYNAK>();
            this.TBLUAKMAS = new HashSet<TBLUAKMAS>();
            this.TBLURETFASONLOJISTIK = new HashSet<TBLURETFASONLOJISTIK>();
            this.TBLURETHAZIRLIKSURE = new HashSet<TBLURETHAZIRLIKSURE>();
            this.TBLURETIM_TOLERANS_LOG = new HashSet<TBLURETIM_TOLERANS_LOG>();
            this.TBLURETISEMRISABITLEME = new HashSet<TBLURETISEMRISABITLEME>();
            this.TBLURETKAYMAMES = new HashSet<TBLURETKAYMAMES>();
            this.TBLURETKURAL = new HashSet<TBLURETKURAL>();
            this.TBLURETMAKKAYES = new HashSet<TBLURETMAKKAYES>();
            this.TBLURETOPKAYES = new HashSet<TBLURETOPKAYES>();
            this.TBLURETOPMAKES = new HashSet<TBLURETOPMAKES>();
            this.TBLURETOTOMATIKMAKINE = new HashSet<TBLURETOTOMATIKMAKINE>();
            this.TBLURETPERMAKES = new HashSet<TBLURETPERMAKES>();
            this.TBLURETROBOTURUNSET = new HashSet<TBLURETROBOTURUNSET>();
            this.TBLURETSERI = new HashSet<TBLURETSERI>();
            this.TBLURETVARDIYA = new HashSet<TBLURETVARDIYA>();
            this.TBLURETVARDIYAETKINLIK = new HashSet<TBLURETVARDIYAETKINLIK>();
            this.TBLVIEWHAK = new HashSet<TBLVIEWHAK>();
            this.TBLWORKPATH = new HashSet<TBLWORKPATH>();
        }
    
        public short SUBE_KODU { get; set; }
        public short ISLETME_KODU { get; set; }
        public string UNVAN { get; set; }
        public string ADRES { get; set; }
        public string ILCE { get; set; }
        public string ULKEKODU { get; set; }
        public string SEHIRKODU { get; set; }
        public string VDAIRE { get; set; }
        public string VNO { get; set; }
        public string WEBADRESI { get; set; }
        public string MERKEZMI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public Nullable<byte> I_YEDEK1 { get; set; }
        public Nullable<short> I_YEDEK2 { get; set; }
        public Nullable<System.DateTime> T_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string AKTIF { get; set; }
        public Nullable<decimal> SERMAYESI { get; set; }
        public string TICARETSICILIADRESI { get; set; }
        public string TICARETSICILINO { get; set; }
        public string UYENO { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string TCNO { get; set; }
    
        public virtual TBLAFATUPRM TBLAFATUPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBAGLANTI> TBLBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCEK> TBLBCEK { get; set; }
        public virtual TBLBCEKNO TBLBCEKNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCEKPARCA> TBLBCEKPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBFORMMAS> TBLBFORMMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBFORMMASEK> TBLBFORMMASEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMDURUM> TBLBKMDURUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMPLAN> TBLBKMPLAN { get; set; }
        public virtual TBLBKMPRM TBLBKMPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMSB> TBLBKMSB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMSOZMAS> TBLBKMSOZMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMSOZTIP> TBLBKMSOZTIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMTALEP> TBLBKMTALEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMTALEPKONTROL> TBLBKMTALEPKONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMTIP> TBLBKMTIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBKMTRA> TBLBKMTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKDESENMAS> TBLBNKDESENMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKHESKSTDETAY> TBLBNKHESKSTDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKHESSABIT> TBLBNKHESSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKHESTRA> TBLBNKHESTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKKURUMMAS> TBLBNKKURUMMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKLOGTRA> TBLBNKLOGTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKMUHVIRMAN> TBLBNKMUHVIRMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKODEPLAN> TBLBNKODEPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKONLOTMODEME> TBLBNKONLOTMODEME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKONLOTMTRANS> TBLBNKONLOTMTRANS { get; set; }
        public virtual TBLBNKPARAMSUBE TBLBNKPARAMSUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKSCENTEGREMAS> TBLBNKSCENTEGREMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKSCENTEGRETRA> TBLBNKSCENTEGRETRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBNKTEMSABIT> TBLBNKTEMSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBSCMODELMAS> TBLBSCMODELMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBSEN> TBLBSEN { get; set; }
        public virtual TBLBSENNO TBLBSENNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBSENPARCA> TBLBSENPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEBILESENROLTRA> TBLBUTCEBILESENROLTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEMAS> TBLBUTCEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEODEPLANMAS> TBLBUTCEODEPLANMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBUTCEROLTRA> TBLBUTCEROLTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCAGRUP> TBLCAGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCAHAR> TBLCAHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKOD1> TBLCARIKOD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKOD2> TBLCARIKOD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKOD3> TBLCARIKOD3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKOD4> TBLCARIKOD4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKOD5> TBLCARIKOD5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKUR> TBLCARIKUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIPLASIYER> TBLCARIPLASIYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARISTOK> TBLCARISTOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCASABIT> TBLCASABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCEKSENDEK> TBLCEKSENDEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCEKSENETTAHESLES> TBLCEKSENETTAHESLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCIZELGETASLAK> TBLCIZELGETASLAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGACIKLAMALAR> TBLCONFIGACIKLAMALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGALTERNATIFGRUP> TBLCONFIGALTERNATIFGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGBAGLANTI> TBLCONFIGBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGBELGELER> TBLCONFIGBELGELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGBIRLIKKALEMMAS> TBLCONFIGBIRLIKKALEMMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGBIRLIKKALEMTRA> TBLCONFIGBIRLIKKALEMTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGDEGER> TBLCONFIGDEGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGKURALLAR> TBLCONFIGKURALLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGMAS> TBLCONFIGMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGOZELLIK> TBLCONFIGOZELLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGPARAMS> TBLCONFIGPARAMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGTRA> TBLCONFIGTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGURUNGRUP> TBLCONFIGURUNGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGURUNGRUPBAGLANTI> TBLCONFIGURUNGRUPBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGURUNGRUPMAMULBAGLANTI> TBLCONFIGURUNGRUPMAMULBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONFIGYENIOZELLIKDEGERLER> TBLCONFIGYENIOZELLIKDEGERLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMADAY> TBLCRMADAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKGRUP> TBLCRMANKGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKICERIK> TBLCRMANKICERIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKICERIKGRUP> TBLCRMANKICERIKGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMANKSABIT> TBLCRMANKSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGELOG> TBLCRMEXCHANGELOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGEMAS> TBLCRMEXCHANGEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGEPRM> TBLCRMEXCHANGEPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMEXCHANGETRA> TBLCRMEXCHANGETRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMFIRSAT> TBLCRMFIRSAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMKAYIPNEDEN> TBLCRMKAYIPNEDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMKULLANP> TBLCRMKULLANP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMPAZAKT> TBLCRMPAZAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMPAZAKT> TBLCRMPAZAKT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMPAZALTAKT> TBLCRMPAZALTAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSABLON> TBLCRMSABLON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSATAKT> TBLCRMSATAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSATASAMASI> TBLCRMSATASAMASI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYAKT> TBLCRMSKYAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYAKTTIP> TBLCRMSKYAKTTIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYDURUM> TBLCRMSKYDURUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYGRUP> TBLCRMSKYGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMSKYSABIT> TBLCRMSKYSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCRMWIZARDDATA> TBLCRMWIZARDDATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGAKTARIMLOG> TBLDAGAKTARIMLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGDISPATCH> TBLDAGDISPATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGFUNCHIST> TBLDAGFUNCHIST { get; set; }
        public virtual TBLDAGPARAM TBLDAGPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGROTAGRUPLARI> TBLDAGROTAGRUPLARI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGROTASABIT> TBLDAGROTASABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGVASITABILGI> TBLDAGVASITABILGI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAMGAVERGISI> TBLDAMGAVERGISI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDBSFATURAMAS> TBLDBSFATURAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDBSFATURATRA> TBLDBSFATURATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDBSLIMITRISK> TBLDBSLIMITRISK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEKOMAS> TBLDEKOMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEKONO> TBLDEKONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEKOTRA> TBLDEKOTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEKOTRAEK> TBLDEKOTRAEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPMAS> TBLDEPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPOKILIT> TBLDEPOKILIT { get; set; }
        public virtual TBLDEPPARAM TBLDEPPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPSAYIM> TBLDEPSAYIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPSAYIMSERI> TBLDEPSAYIMSERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPTESAYRIBAKIYE> TBLDEPTESAYRIBAKIYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDIZAYNMOD> TBLDIZAYNMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDIZAYNSABIT> TBLDIZAYNSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDZNBASIMLOG> TBLDZNBASIMLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEARSIV> TBLEARSIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEATIK> TBLEATIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEFATPRM> TBLEFATPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEFATURA> TBLEFATURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEFATZARF> TBLEFATZARF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMUSTAHSIL> TBLEMUSTAHSIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMUTABAKATLOG> TBLEMUTABAKATLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMUTABAKATMAS> TBLEMUTABAKATMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMUTABAKATSUBETANIM> TBLEMUTABAKATSUBETANIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLENETOZELDURUM> TBLENETOZELDURUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLENETPORTLETMAS> TBLENETPORTLETMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLENETSEPET> TBLENETSEPET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLENETSIPSABLON> TBLENETSIPSABLON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPOSTALOG> TBLEPOSTALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLESNYAPNUM> TBLESNYAPNUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFAILUREPREQUISITION> TBLFAILUREPREQUISITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUEK> TBLFATUEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUIRS> TBLFATUIRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUIRSEK> TBLFATUIRSEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUSERI> TBLFATUSERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUVADE> TBLFATUVADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFIATGRUP> TBLFIATGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFINANSTEMP> TBLFINANSTEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFIYATLISTINFO> TBLFIYATLISTINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFIYFARKMAS> TBLFIYFARKMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHALMASRAFEK> TBLHALMASRAFEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHASHTAGTRA> TBLHASHTAGTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHESKODESLES> TBLHESKODESLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIMZALOG> TBLIMZALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLINDKDVLOG> TBLINDKDVLOG { get; set; }
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLKAMBBCEK TBLKAMBBCEK { get; set; }
        public virtual TBLKAMBBSEN TBLKAMBBSEN { get; set; }
        public virtual TBLKAMBMCEK TBLKAMBMCEK { get; set; }
        public virtual TBLKAMBMSEN TBLKAMBMSEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKAMYONSB> TBLKAMYONSB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKANTPRM> TBLKANTPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKARGOISLEM> TBLKARGOISLEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKARGOKULLANICI> TBLKARGOKULLANICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKARTODEMETRA> TBLKARTODEMETRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASA> TBLKASA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASAEK> TBLKASAEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASAMAS> TBLKASAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKEFILTRA> TBLKEFILTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKODEKRANBAGLANTI> TBLKODEKRANBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKODHARICHAR> TBLKODHARICHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKOSTIPMAS> TBLKOSTIPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKOSULMAS> TBLKOSULMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKOSVADEMAS> TBLKOSVADEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTODEME> TBLKRTODEME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTSOZMAS> TBLKRTSOZMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTTHSLT> TBLKRTTHSLT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKRTTHSLTEK> TBLKRTTHSLTEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULEMAIL> TBLKULEMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULHAKDEVIR> TBLKULHAKDEVIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANHAKP> TBLKULLANHAKP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANHAKTALEP> TBLKULLANHAKTALEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANP> TBLKULLANP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANPROGP> TBLKULLANPROGP { get; set; }
        public virtual TBLKULPARAM TBLKULPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKVKK> TBLKVKK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLOCKEDDATAMAS> TBLLOCKEDDATAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLOGKULTABLOLAR> TBLLOGKULTABLOLAR { get; set; }
        public virtual TBLLOGPARAM TBLLOGPARAM { get; set; }
        public virtual TBLMAGAZALAR TBLMAGAZALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKBKM> TBLMAKBKM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKBKMMASRAFFAT> TBLMAKBKMMASRAFFAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKKATSAYI> TBLMAKKATSAYI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKMALIYET> TBLMAKMALIYET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKMSRMAS> TBLMAKMSRMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKSARF> TBLMAKSARF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALISIRA> TBLMALISIRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMASRAF> TBLMASRAF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMASRAFMAS> TBLMASRAFMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMCEK> TBLMCEK { get; set; }
        public virtual TBLMCEKNO TBLMCEKNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMCEKPARCA> TBLMCEKPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMPSONCELIK> TBLMPSONCELIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPSIPBELGELOG> TBLMRPSIPBELGELOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMSEN> TBLMSEN { get; set; }
        public virtual TBLMSENNO TBLMSENNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMSENPARCA> TBLMSENPARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHAGEC> TBLMUHAGEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHAREF> TBLMUHAREF { get; set; }
        public virtual TBLMUHARES TBLMUHARES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHFIS> TBLMUHFIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHFISEK> TBLMUHFISEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUHMAS> TBLMUHMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUPLAN> TBLMUPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUPLANSUBE> TBLMUPLANSUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSCIRO> TBLMUSCIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTAHSI> TBLMUSTAHSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTAHSIEK> TBLMUSTAHSIEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTERIMAYARLAR> TBLMUSTERIMAYARLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTOZELKESINTI> TBLMUSTOZELKESINTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTOZELKESPROJE> TBLMUSTOZELKESPROJE { get; set; }
        public virtual TBLMUSTPRM TBLMUSTPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTPRMEK> TBLMUSTPRMEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNAKITAKIS_GELIRGIDERTIP> TBLNAKITAKIS_GELIRGIDERTIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNAKITAKISMAS> TBLNAKITAKISMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNAKLIYE> TBLNAKLIYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNDIBAGLANTI> TBLNDIBAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNDS> TBLNDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNETSISLOG> TBLNETSISLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNFDMAS> TBLNFDMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNPMRELMAS> TBLNPMRELMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNRPSHARING> TBLNRPSHARING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNTFPOOL> TBLNTFPOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLODEEMIR> TBLODEEMIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLONLINEBANKLOG> TBLONLINEBANKLOG { get; set; }
        public virtual TBLPARAM TBLPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPOSAKTARILANLAR> TBLPOSAKTARILANLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPOSPARAM> TBLPOSPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRGPRM> TBLPRGPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRJDETAYSABLON> TBLPRJDETAYSABLON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRJKUMULEMAS> TBLPRJKUMULEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRJKUMULETRA> TBLPRJKUMULETRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPROFORMAMAS> TBLPROFORMAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPROFORMATRA> TBLPROFORMATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRAPORSONUC> TBLRAPORSONUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRAPORTASLAK> TBLRAPORTASLAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRCPCONSUSERTRA> TBLRCPCONSUSERTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRCPMAS> TBLRCPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRECMALIYET> TBLRECMALIYET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREPLANISH> TBLREPLANISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREPORTSHARING> TBLREPORTSHARING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREVNO> TBLREVNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLROTABAGLANTI> TBLROTABAGLANTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLROTAMAS> TBLROTAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLROTATRA> TBLROTATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSABLONMAS> TBLSABLONMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAHAACIKLAMA> TBLSAHAACIKLAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATCIRO> TBLSATCIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISTANUSK> TBLSATISTANUSK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAYIM> TBLSAYIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAYIMSERI> TBLSAYIMSERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSERINUM> TBLSERINUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSERITRA> TBLSERITRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSEVKMAS> TBLSEVKMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSEVKTRA> TBLSEVKTRA { get; set; }
        public virtual TBLSFATUPRM TBLSFATUPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSILINENKAYITLAR> TBLSILINENKAYITLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPAMAS> TBLSIPAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPATRA> TBLSIPATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSMSLOG> TBLSMSLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSMSMAS> TBLSMSMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSMSPHONELIST> TBLSMSPHONELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSMSTRA> TBLSMSTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSSATIRAC> TBLSSATIRAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTGRUP> TBLSTGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTHAR> TBLSTHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOK_MADABC> TBLSTOK_MADABC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKDP> TBLSTOKDP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKKOD1> TBLSTOKKOD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKKOD2> TBLSTOKKOD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKKOD3> TBLSTOKKOD3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKKOD4> TBLSTOKKOD4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKKOD5> TBLSTOKKOD5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKURS> TBLSTOKURS { get; set; }
        public virtual TBLSTOKURSNO TBLSTOKURSNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTSABIT> TBLSTSABIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACIKREC> TBLACIKREC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAL12> TBLAL12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDAGYUKNO> TBLDAGYUKNO { get; set; }
        public virtual TBLDETANAL TBLDETANAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEFATUNO> TBLEFATUNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEIRSYANITNO> TBLEIRSYANITNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLESNYAPNUMSTOK> TBLESNYAPNUMSTOK { get; set; }
        public virtual TBLFATUISK TBLFATUISK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATUNO> TBLFATUNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLGENPOSPARAM> TBLGENPOSPARAM { get; set; }
        public virtual TBLIMALAT TBLIMALAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAKBLGNO> TBLMAKBLGNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMAL12> TBLMAL12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALCIRO> TBLMALCIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_MUHAGEC> TEMP_MUHAGEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSMAL> TBLMUSMAL { get; set; }
        public virtual TBLMUSTNO TBLMUSTNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMZAMBAR> TBLMZAMBAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOZELKOD2KDVHESAP> TBLOZELKOD2KDVHESAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPLANLAMA_RAPORU_DETAY> TBLPLANLAMA_RAPORU_DETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPLANLAMA_RAPORU_ICMAL> TBLPLANLAMA_RAPORU_ICMAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLGENPOSODEME> TBLGENPOSODEME { get; set; }
        public virtual TBLPOSKUMULE TBLPOSKUMULE { get; set; }
        public virtual TBLPOSTEMP TBLPOSTEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPPRJKUMULE> TBLTMPPRJKUMULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAT12> TBLSAT12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATMAL> TBLSATMAL { get; set; }
        public virtual TBLSIP12TMP TBLSIP12TMP { get; set; }
        public virtual TBLSIP12TOP TBLSIP12TOP { get; set; }
        public virtual TBLSIPDETAY TBLSIPDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPMALMUS> TBLSIPMALMUS { get; set; }
        public virtual TBLSIPTTOP TBLSIPTTOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTMUHDETAY> TBLSTMUHDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTOKPH> TBLSTOKPH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSUBISEMRI> TBLSUBISEMRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETSUBOPERATIONS> TBLURETSUBOPERATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSWIFTDOCMAS> TBLSWIFTDOCMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFMAS> TBLTEKLIFMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFPRM> TBLTEKLIFPRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEKLIFTRA> TBLTEKLIFTRA { get; set; }
        public virtual TBLTEMPBAG TBLTEMPBAG { get; set; }
        public virtual TBLTEMPHAIS TBLTEMPHAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTERAZIPARAM> TBLTERAZIPARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTEVKIFATKDVKOD> TBLTEVKIFATKDVKOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTIPDETAY> TBLTIPDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPBNKSCENTEGREMAS> TBLTMPBNKSCENTEGREMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPBNKSCENTEGRETRA> TBLTMPBNKSCENTEGRETRA { get; set; }
        public virtual TBLTMPDAGIT TBLTMPDAGIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDBSFATURAMAS> TBLTMPDBSFATURAMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDBSFATURATRA> TBLTMPDBSFATURATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDBSLIMITRISK> TBLTMPDBSLIMITRISK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPDISSIPATRA> TBLTMPDISSIPATRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTMPEMIR> TBLTMPEMIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUAKKAYNAK> TBLUAKKAYNAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUAKMAS> TBLUAKMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETFASONLOJISTIK> TBLURETFASONLOJISTIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETHAZIRLIKSURE> TBLURETHAZIRLIKSURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETIM_TOLERANS_LOG> TBLURETIM_TOLERANS_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETISEMRISABITLEME> TBLURETISEMRISABITLEME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETKAYMAMES> TBLURETKAYMAMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETKURAL> TBLURETKURAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETMAKKAYES> TBLURETMAKKAYES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETOPKAYES> TBLURETOPKAYES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETOPMAKES> TBLURETOPMAKES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETOTOMATIKMAKINE> TBLURETOTOMATIKMAKINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETPERMAKES> TBLURETPERMAKES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETROBOTURUNSET> TBLURETROBOTURUNSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETSERI> TBLURETSERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETVARDIYA> TBLURETVARDIYA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURETVARDIYAETKINLIK> TBLURETVARDIYAETKINLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLVIEWHAK> TBLVIEWHAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLWORKPATH> TBLWORKPATH { get; set; }
    }
}
