//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIPATRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSIPATRA()
        {
            this.MGSIPATRA = new HashSet<MGSIPATRA>();
            this.TBLISEMRIREZERVESTOK = new HashSet<TBLISEMRIREZERVESTOK>();
            this.TBLSIPARISREZERVESTOK = new HashSet<TBLSIPARISREZERVESTOK>();
        }
    
        public string STOK_KODU { get; set; }
        public string FISNO { get; set; }
        public Nullable<decimal> STHAR_GCMIK { get; set; }
        public Nullable<decimal> STHAR_GCMIK2 { get; set; }
        public Nullable<decimal> CEVRIM { get; set; }
        public string STHAR_GCKOD { get; set; }
        public System.DateTime STHAR_TARIH { get; set; }
        public Nullable<decimal> STHAR_NF { get; set; }
        public Nullable<decimal> STHAR_BF { get; set; }
        public Nullable<decimal> STHAR_IAF { get; set; }
        public Nullable<decimal> STHAR_KDV { get; set; }
        public Nullable<short> DEPO_KODU { get; set; }
        public string STHAR_ACIKLAMA { get; set; }
        public Nullable<decimal> STHAR_SATISK { get; set; }
        public Nullable<decimal> STHAR_MALFISK { get; set; }
        public string STHAR_FTIRSIP { get; set; }
        public Nullable<decimal> STHAR_SATISK2 { get; set; }
        public Nullable<byte> LISTE_FIAT { get; set; }
        public string STHAR_HTUR { get; set; }
        public Nullable<byte> STHAR_DOVTIP { get; set; }
        public Nullable<byte> PROMASYON_KODU { get; set; }
        public Nullable<decimal> STHAR_DOVFIAT { get; set; }
        public Nullable<short> STHAR_ODEGUN { get; set; }
        public Nullable<decimal> STRA_SATISK3 { get; set; }
        public Nullable<decimal> STRA_SATISK4 { get; set; }
        public Nullable<decimal> STRA_SATISK5 { get; set; }
        public Nullable<decimal> STRA_SATISK6 { get; set; }
        public string STHAR_BGTIP { get; set; }
        public string STHAR_KOD1 { get; set; }
        public string STHAR_KOD2 { get; set; }
        public string STHAR_SIPNUM { get; set; }
        public string STHAR_CARIKOD { get; set; }
        public string STHAR_SIP_TURU { get; set; }
        public string PLASIYER_KODU { get; set; }
        public string EKALAN_NEDEN { get; set; }
        public string EKALAN { get; set; }
        public string EKALAN1 { get; set; }
        public Nullable<decimal> REDMIK { get; set; }
        public Nullable<byte> REDNEDEN { get; set; }
        public Nullable<short> SIRA { get; set; }
        public Nullable<short> STRA_SIPKONT { get; set; }
        public string AMBAR_KABULNO { get; set; }
        public Nullable<byte> FIRMA_DOVTIP { get; set; }
        public Nullable<decimal> FIRMA_DOVTUT { get; set; }
        public Nullable<decimal> FIRMA_DOVMAL { get; set; }
        public string UPDATE_KODU { get; set; }
        public string IRSALIYE_NO { get; set; }
        public Nullable<System.DateTime> IRSALIYE_TARIH { get; set; }
        public string KOSULKODU { get; set; }
        public Nullable<byte> ECZA_FAT_TIP { get; set; }
        public Nullable<System.DateTime> STHAR_TESTAR { get; set; }
        public Nullable<byte> OLCUBR { get; set; }
        public int INCKEYNO { get; set; }
        public Nullable<System.DateTime> VADE_TARIHI { get; set; }
        public string LISTE_NO { get; set; }
        public Nullable<int> BAGLANTI_NO { get; set; }
        public short SUBE_KODU { get; set; }
        public string MUH_KODU { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK5 { get; set; }
        public string C_YEDEK6 { get; set; }
        public Nullable<byte> B_YEDEK7 { get; set; }
        public Nullable<short> I_YEDEK8 { get; set; }
        public Nullable<int> L_YEDEK9 { get; set; }
        public Nullable<System.DateTime> D_YEDEK10 { get; set; }
        public string PROJE_KODU { get; set; }
        public Nullable<System.DateTime> FIYATTARIHI { get; set; }
        public Nullable<System.DateTime> KOSULTARIHI { get; set; }
        public Nullable<short> SATISK1TIP { get; set; }
        public Nullable<short> SATISK2TIP { get; set; }
        public Nullable<short> SATISK3TIP { get; set; }
        public Nullable<short> SATISK4TIP { get; set; }
        public Nullable<short> SATISK5TIP { get; set; }
        public Nullable<short> SATISK6TIP { get; set; }
        public Nullable<byte> EXPORTTYPE { get; set; }
        public Nullable<decimal> EXPORTMIK { get; set; }
        public string ONAYTIPI { get; set; }
        public int ONAYNUM { get; set; }
        public Nullable<decimal> KKMALF { get; set; }
        public Nullable<short> STRA_IRSKONT { get; set; }
        public string YAPKOD { get; set; }
        public string MAMYAPKOD { get; set; }
        public Nullable<decimal> OTVFIYAT { get; set; }
        public Nullable<int> IRS_INCKEYNO { get; set; }
        public string YEDEK11 { get; set; }
        public string YEDEK12 { get; set; }
        public Nullable<int> YEDEK13 { get; set; }
        public Nullable<int> YEDEK14 { get; set; }
        public Nullable<double> YEDEK15 { get; set; }
        public Nullable<double> YEDEK16 { get; set; }
        public Nullable<System.DateTime> YEDEK17 { get; set; }
        public Nullable<System.DateTime> YEDEK18 { get; set; }
        public string YEDEK19 { get; set; }
        public string YEDEK20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGSIPATRA> MGSIPATRA { get; set; }
        public virtual TBLESNYAPMAS TBLESNYAPMAS { get; set; }
        public virtual TBLESNYAPMAS TBLESNYAPMAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISEMRIREZERVESTOK> TBLISEMRIREZERVESTOK { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPARISREZERVESTOK> TBLSIPARISREZERVESTOK { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
