//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTMPPRJKUMULE
    {
        public short ISLETME_KODU { get; set; }
        public short SUBE_KODU { get; set; }
        public string RAPORKOD { get; set; }
        public short SIRANO { get; set; }
        public string VTISIM { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string BIRIM { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> FIRMADOVTUT { get; set; }
        public Nullable<short> DOVTIP { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string CYEDEK1 { get; set; }
        public string CYEDEK2 { get; set; }
        public Nullable<int> IYEDEK1 { get; set; }
        public Nullable<int> IYEDEK2 { get; set; }
        public Nullable<int> IYEDEK3 { get; set; }
        public Nullable<int> IYEDEK4 { get; set; }
        public Nullable<decimal> FYEDEK1 { get; set; }
        public Nullable<decimal> FYEDEK2 { get; set; }
        public Nullable<decimal> FYEDEK3 { get; set; }
        public Nullable<decimal> FYEDEK4 { get; set; }
        public Nullable<System.DateTime> TYEDEK1 { get; set; }
        public Nullable<System.DateTime> TYEDEK2 { get; set; }
        public Nullable<System.DateTime> TYEDEK3 { get; set; }
        public Nullable<System.DateTime> TYEDEK4 { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLPRJKUMULETRA TBLPRJKUMULETRA { get; set; }
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
