//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTMPFIRMACEK
    {
        public short SUBE_KODU { get; set; }
        public string SC_NO { get; set; }
        public string TAHSILNO { get; set; }
        public string TAHBANKA { get; set; }
        public string TAHSUBE { get; set; }
        public string TAHSILHES { get; set; }
        public Nullable<System.DateTime> SC_GIRTRH { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string SC_VERENK { get; set; }
        public string SC_ABORCLU { get; set; }
        public string CEKMICR { get; set; }
        public string CEKBANKA { get; set; }
        public string YERI { get; set; }
        public string CEKSUBE { get; set; }
        public string CEKHESAP { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public string PLASIYER_KODU { get; set; }
        public string PROJE_KODU { get; set; }
        public string DURUM { get; set; }
        public string AC { get; set; }
    }
}
