//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTMPEMIR
    {
        public Nullable<int> ODEINCKEYNO { get; set; }
        public int HARINCKEYNO { get; set; }
        public Nullable<System.DateTime> VTARIH { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<short> SUBE_KODU { get; set; }
    
        public virtual TBLSUBELER TBLSUBELER { get; set; }
    }
}
