//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURMPAR
    {
        public short ISLETME_KODU { get; set; }
        public string MAL_CINS1 { get; set; }
        public string MAL_CINS2 { get; set; }
        public Nullable<short> HATSUBE { get; set; }
        public Nullable<byte> HASS { get; set; }
        public string LOKAL_DEPO { get; set; }
        public string REC_SAKLA { get; set; }
        public Nullable<short> LDEPO_1 { get; set; }
        public Nullable<short> LDEPO_2 { get; set; }
        public Nullable<short> LDEPO_3 { get; set; }
        public Nullable<short> LDEPO_4 { get; set; }
        public Nullable<short> LDEPO_5 { get; set; }
        public Nullable<short> LDEPO_6 { get; set; }
        public Nullable<short> LDEPO_7 { get; set; }
        public Nullable<short> LDEPO_8 { get; set; }
        public Nullable<short> LDEPO_9 { get; set; }
        public Nullable<short> LDEPO_10 { get; set; }
        public Nullable<short> LDEPO_11 { get; set; }
        public Nullable<short> LDEPO_12 { get; set; }
        public Nullable<short> LDEPO_13 { get; set; }
        public Nullable<short> LDEPO_14 { get; set; }
        public Nullable<short> LDEPO_15 { get; set; }
        public Nullable<byte> SUBE_1 { get; set; }
        public Nullable<byte> SUBE_2 { get; set; }
        public Nullable<byte> SUBE_3 { get; set; }
        public Nullable<byte> SUBE_4 { get; set; }
        public Nullable<byte> SUBE_5 { get; set; }
        public Nullable<byte> SUBE_6 { get; set; }
        public Nullable<byte> SUBE_7 { get; set; }
        public Nullable<byte> SUBE_8 { get; set; }
        public Nullable<byte> SUBE_9 { get; set; }
        public Nullable<byte> SUBE_10 { get; set; }
        public Nullable<byte> SUBE_11 { get; set; }
        public Nullable<byte> SUBE_12 { get; set; }
        public Nullable<byte> SUBE_13 { get; set; }
        public Nullable<byte> SUBE_14 { get; set; }
        public Nullable<byte> SUBE_15 { get; set; }
        public Nullable<byte> HASSTUT { get; set; }
        public string MUHENTEG { get; set; }
        public string MKOD { get; set; }
        public string HKOD { get; set; }
        public string MIK { get; set; }
        public string HANGIMIK { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public string C_YEDEK4 { get; set; }
        public string C_YEDEK5 { get; set; }
        public string C_YEDEK6 { get; set; }
        public string C_YEDEK7 { get; set; }
        public string C_YEDEK8 { get; set; }
        public string C_YEDEK9 { get; set; }
        public string C_YEDEK10 { get; set; }
        public Nullable<short> URETDEPO { get; set; }
        public string DAT_ISEMRIBAKTAKIP { get; set; }
        public string USK_ISEMRIBAKTAKIP { get; set; }
        public string BARKODLUISLEM { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string ISFAZLAURYAP { get; set; }
        public Nullable<decimal> FAZLAURORAN { get; set; }
        public string MRPTALEPOLUS { get; set; }
        public string MIKDEFALAN { get; set; }
        public string USK_RAP_BAK_GOSTER { get; set; }
        public string REC_TEKSEVIYE_SAKLA { get; set; }
        public string MALIYET_ALISFIYAT1 { get; set; }
        public string TARIHSELBAKIYE { get; set; }
        public string USK_TEKSEVIYE_KULLAN { get; set; }
        public string ISEMRINE_BAGLI_USK { get; set; }
        public string ISEMRI_MIKTARI_POLITIKASI { get; set; }
        public string ISEMRI_TARIH_POLITIKASI { get; set; }
        public string KILITLI_MAMUL { get; set; }
        public string KILITLI_BILESEN { get; set; }
        public string USTISEMRIKULLANIMI { get; set; }
        public string ALTRECALAN { get; set; }
        public string ISFAZLASIPURYAP { get; set; }
        public string YAYIMLANDI_ISEMRI_DEGIS { get; set; }
        public string USK_ASGARI_STOK_KONTROL { get; set; }
        public string ISEMRI_BAG_KAPAT { get; set; }
        public string STOK_DEPO_KONTROL { get; set; }
        public string YAYIMLANDI_ISEMRI_DEGIS_TARIH { get; set; }
        public string BELGESERIGETIR { get; set; }
        public string MALZEMETALEP_SERIOLUSTUR { get; set; }
        public string FIREDETAY { get; set; }
        public string ARALIKLIFIRETANIMI { get; set; }
        public string DAT_TRANSFER_ONAYI { get; set; }
        public string DEPO_STPLAN { get; set; }
        public string OTO_KAY_GIR { get; set; }
        public string REFISEMRI_SIL { get; set; }
        public string MALIYETYUZDEKULLAN { get; set; }
        public string FIREDEPOKULLAN { get; set; }
        public string FIREDEPO_FISSERISI { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
    }
}
