//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURETKAYNAKHAR
    {
        public int INCKEYNO { get; set; }
        public short ISLETME_KODU { get; set; }
        public int KAYNAK_ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string GCKOD { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> OMUR { get; set; }
        public string HAREKET_TIPI { get; set; }
        public string BELGE_NO { get; set; }
        public Nullable<short> BELGE_KONT { get; set; }
        public Nullable<int> UAK_ID { get; set; }
        public Nullable<int> USK_ID { get; set; }
        public Nullable<int> STHAR_INCKEYNO { get; set; }
        public Nullable<int> GOZ_SAYISI { get; set; }
        public string TAMIR_SEBEBI { get; set; }
        public string ARIZA_KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public string C_YEDEK3 { get; set; }
        public string C_YEDEK4 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        public virtual TBLMRPISCI TBLMRPISCI { get; set; }
    }
}
