//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURMSUBEDEPOFABRIKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURMSUBEDEPOFABRIKA()
        {
            this.TBLCIZELGETASLAK = new HashSet<TBLCIZELGETASLAK>();
            this.TBLMRPPLAN = new HashSet<TBLMRPPLAN>();
            this.TBLSUBISEMRI = new HashSet<TBLSUBISEMRI>();
            this.TBLURMSUBEDEPO = new HashSet<TBLURMSUBEDEPO>();
            this.TBLBCK_MGPMAS = new HashSet<TBLBCK_MGPMAS>();
            this.TBLBCK_MRP_DETAIL = new HashSet<TBLBCK_MRP_DETAIL>();
            this.TBLBCK_MRP = new HashSet<TBLBCK_MRP>();
            this.TBLBCK_MRP_REZERVE_BAKIYE = new HashSet<TBLBCK_MRP_REZERVE_BAKIYE>();
            this.TBLBCK_MRPPLAN = new HashSet<TBLBCK_MRPPLAN>();
            this.TBLBCK_MRPSIP = new HashSet<TBLBCK_MRPSIP>();
            this.TBLBCK_MRPSIP_PLAN_BAGDATA = new HashSet<TBLBCK_MRPSIP_PLAN_BAGDATA>();
            this.TBLMGPMAS = new HashSet<TBLMGPMAS>();
            this.TBLMRP_DETAIL = new HashSet<TBLMRP_DETAIL>();
            this.TBLMRP = new HashSet<TBLMRP>();
            this.TBLMRP_REZERVE_BAKIYE = new HashSet<TBLMRP_REZERVE_BAKIYE>();
            this.TBLMRPSIP = new HashSet<TBLMRPSIP>();
        }
    
        public short ISLETME_KODU { get; set; }
        public string FABRIKA_KODU { get; set; }
        public string FABRIKA_ACIKLAMA { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK1 { get; set; }
        public Nullable<decimal> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCIZELGETASLAK> TBLCIZELGETASLAK { get; set; }
        public virtual TBLISLETMELER TBLISLETMELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPPLAN> TBLMRPPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSUBISEMRI> TBLSUBISEMRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURMSUBEDEPO> TBLURMSUBEDEPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MGPMAS> TBLBCK_MGPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRP_DETAIL> TBLBCK_MRP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRP> TBLBCK_MRP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRP_REZERVE_BAKIYE> TBLBCK_MRP_REZERVE_BAKIYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRPPLAN> TBLBCK_MRPPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRPSIP> TBLBCK_MRPSIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBCK_MRPSIP_PLAN_BAGDATA> TBLBCK_MRPSIP_PLAN_BAGDATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMGPMAS> TBLMGPMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRP_DETAIL> TBLMRP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRP> TBLMRP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRP_REZERVE_BAKIYE> TBLMRP_REZERVE_BAKIYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMRPSIP> TBLMRPSIP { get; set; }
    }
}
