//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURTYENIALANTABLO
    {
        public string TABLOADI { get; set; }
        public string ALANADI { get; set; }
        public string ZORUNLU { get; set; }
        public string AKTIF { get; set; }
        public int GOSTERSIRASI { get; set; }
        public string VTDEGISTI { get; set; }
        public string KAYITYAPANKUL { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string DUZELTMEYAPANKUL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string C_YEDEK1 { get; set; }
        public string C_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK4 { get; set; }
        public Nullable<decimal> F_YEDEK5 { get; set; }
        public Nullable<decimal> F_YEDEK6 { get; set; }
        public Nullable<System.DateTime> D_YEDEK7 { get; set; }
        public Nullable<System.DateTime> D_YEDEK8 { get; set; }
        public string V_YEDEK10 { get; set; }
        public string V_YEDEK11 { get; set; }
        public Nullable<int> FATALANNO { get; set; }
        public byte TIP { get; set; }
        public string GRUPBASLIK { get; set; }
        public string LINK { get; set; }
        public string LINKDATA { get; set; }
        public string EKREHBER { get; set; }
        public Nullable<byte> TUS { get; set; }
        public Nullable<byte> SIRA { get; set; }
    
        public virtual TBLURTYENIALAN TBLURTYENIALAN { get; set; }
    }
}
