//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_COUNTTRANS
    {
        public int ID { get; set; }
        public int COUNTREF { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<int> ITEMREF { get; set; }
        public string ITEMCODE { get; set; }
        public string WHCODE { get; set; }
        public Nullable<int> WHREF { get; set; }
        public string ADDRESS { get; set; }
        public string PALLET { get; set; }
        public Nullable<int> VARIANTREF { get; set; }
        public string VARIANTCODE { get; set; }
        public string TRACKINGNUMBER { get; set; }
        public Nullable<int> UNITREF { get; set; }
        public string UNITCODE { get; set; }
        public Nullable<decimal> CONVFACT1 { get; set; }
        public Nullable<decimal> CONVFACT2 { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<int> USERREF { get; set; }
        public string USERCODE { get; set; }
        public string FIRM { get; set; }
        public string PERIOD { get; set; }
        public short STATUS { get; set; }
        public int PALLETTYPE { get; set; }
        public Nullable<System.DateTime> EXPIRATIONDATE { get; set; }
        public string COUNTGUID { get; set; }
        public string COUNTTRANSGUID { get; set; }
    }
}
