//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellResim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_OPERATIONSCORE
    {
        public int ID { get; set; }
        public string FIRM { get; set; }
        public Nullable<decimal> ENTRYMAINUNITSCORE { get; set; }
        public Nullable<decimal> ENTRYSKUSCORE { get; set; }
        public Nullable<decimal> OUTPUTMAINUNITSCORE { get; set; }
        public Nullable<decimal> OUTPUTSKUSCORE { get; set; }
        public Nullable<decimal> PLACEMENTMAINUNITSCORE { get; set; }
        public Nullable<decimal> PLACEMENTSKUSCORE { get; set; }
        public Nullable<decimal> PRODUCTIONMAINUNITSCORE { get; set; }
        public Nullable<decimal> PRODUCTIONSKUSCORE { get; set; }
    }
}
